### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by ldh1983** [Toperlock/sing-box-subscribe#10]
现在有大部分moji都加不上，只有香港的能加上。

**Comment by Toperlock** [comment]
原本节点名是什么，发给我看看为啥不行

**Comment by ldh1983** [comment]
"🇭🇰 2香港-专线(iOS优化)",
        "5台湾-联通/移动(新协议)",
        "🇭🇰 HK vmg",
        "US vmg",
这个样子，香港的行，其它不行。之前的都可以。汉字，像TW,US这样的大写都能刷出emoji。

**Comment by Toperlock** [comment]
再试试，修好了。最近在适配给越南人用，脑子糊涂了写错了
