### ISSUE TITLE
  "outbounds"中 "tag":"Proxy"的出站，转换后始终会包含所有的节点。

### ISSUE THREAD

**Issue by Flying-Pika** [Toperlock/sing-box-subscribe#102]
### 描述

  "outbounds": [
    {
      "tag":"Proxy",
      "type":"selector",
      "outbounds":[
        "auto",
        "direct",
        "{all}"
      ]
    }

这一块配置转换出来的节点，无论是否包含 "{all}" 这个出站，转换出来的配置都会包含所有的节点，后面的tag 则不会。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
之前添加`subgroup`字段忽略的问题。
你可以试试`subgroup`功能
![image](https://github.com/user-attachments/assets/25dba6ac-0b92-4a9d-acc1-2d4240684678)

**Comment by Flying-Pika** [comment]
感谢，但是我目前是build成docker镜像 运行的后端，希望拼接成url 来订阅，这样我多端只维护一份配置文件就好， 目前看url拼接不支持subgroup 参数， 有没有什么方式 让url拼接 远程读取providers.json文件呢？

**Comment by Toperlock** [comment]
那不行
