### ISSUE TITLE
转换失败

### ISSUE THREAD

**Issue by An-ding-S** [Toperlock/sing-box-subscribe#103]
### 描述

更新后转换失败。什么节点都不行了。咋回事？

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
排除订阅是不是正常能在clash运行

私聊[tg](tg://user?id=6489302239)
