### ISSUE TITLE
作者你好，我Fork了你的这个仓库，是否可以自己修改配置文件的模板呢？

### ISSUE THREAD

**Issue by 7sasuke7l** [Toperlock/sing-box-subscribe#104]
### 描述

我Fork到仓库后，是否可以自己修改这个config_template_groups_rule_set_tun.json文件，我遇到的问题是，一旦我做出修改，用sing-box客户端订阅时，就会报错。尤其是出站规则，因为我的节点很少，不需要设置很多国家筛选，我想删除掉这些国家的tag.

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
截图看看提示什么报错

**Comment by Toperlock** [comment]
[rule_set_tun_lite.json](https://github.com/user-attachments/files/17097041/rule_set_tun_lite.json)
