### ISSUE TITLE
不知道为啥 拉取新的迭代之后 就一直提示"status": "error" 起先以为是我的配置文件有问题 但是然后试了自带的配置文件也报错

### ISSUE THREAD

**Issue by Lobs1994** [Toperlock/sing-box-subscribe#106]
### 描述

{
    "status": "error"
}

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
你用这个免费订阅链接
https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/dy/main/jd
是正常的吗

**Comment by Toperlock** [comment]
要么就是你的订阅获取超时
你家订阅vercel获取不了

**Comment by Lobs1994** [comment]
> 你用这个免费订阅链接 https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/dy/main/jd 是正常的吗

不正常，这个订阅的2条节点好像都没法被v2ray 和clash nekobox等软件所识别   该订阅是什么软件的订阅地址？

**Comment by Lobs1994** [comment]
> 只有"status": "error" 没有显示'message'？

是的  我访问主域名填写
{
    "subscribes": [
        {
            "url": "https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/dy/main/jd",
            "tag": "tag_1",
            "enabled": true,
            "emoji": 1,
            "subgroup": "",
            "prefix": "",
            "User-Agent": "v2rayng"
        }
    ],
    "auto_set_outbounds_dns": {
        "proxy": "",
        "direct": ""
    },
    "save_config_path": "./config.json",
    "auto_backup": false,
    "exclude_protocol": "ssr",
    "config_template": "",
    "Only-nodes": false
}


保存后提示{"status":"success"}  但结果还是{
"status": "error"
}

**Comment by Toperlock** [comment]
把你的vercel项目删了，重新导入

**Comment by Lobs1994** [comment]
> 把你的vercel项目删掉，重新导入

OK 可以了  莫名奇妙的故障  但是我得等我域名生效了   但是https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/dy/main/jd这个链接好像还是读不到节点
