### ISSUE TITLE
既然是自建服务器，何不去掉网页端，直接用配置文件

### ISSUE THREAD

**Issue by jarryson** [Toperlock/sing-box-subscribe#11]
用配置文件或者传递url参数，跟其他订阅转换一样，可以通过客户端直接更新，而不需要手动更新了。

可以替代clash了。

**Comment by Toperlock** [comment]
没用数据库，不能返回一个远程配置链接，此脚本只是生成一次性的singbox配置，不能热更新。
后续也没打算加数据库。对我来说够用了

**Comment by Toperlock** [comment]
有灵感了，到时候改进
