### ISSUE TITLE
config后面是否可以跟多个URL_LINK

### ISSUE THREAD

**Issue by bupt2017** [Toperlock/sing-box-subscribe#110]
### 描述

/config/URL_LINK&emoji=1&prefix=♥&ua=v2rayng&eps=vmess,hy2&enn=网站,剩余流量&file=https://xxxxxxxxx.json
使用文档里面这个格式可以生成配置直链，但是有多个机场链接的话该如何操作呢，望大佬指点

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
[readme](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#20231104-update-two-sub-links-can-be-processed-the-format-is-configurl-encoding-emoji-tag-prefix-ua-parameters-cannot-be-written-supports-3-sub-links-by-202411)

**Comment by bupt2017** [comment]
感谢大佬，是我没看仔细
