### ISSUE TITLE
hy2 的节点不生成端口跳跃的配置

### ISSUE THREAD

**Issue by Fdulo** [Toperlock/sing-box-subscribe#112]
### 描述

订阅转换sing-box配置 hy2 的节点不生成带有端口跳跃的配置

使用转换格式: `https://xxxxxxx.vercel.app/config/https://xxxxxxsubscribe?token=123456&ua=clashmeta&file=.json配置`

(原订阅在sing-box可直接生成支持配置) 

转换后的订阅服务器出站部分
```json
{
      "tag": "某国丨Hy2",
      "type": "hysteria2",
      "server": "服务器",
      "server_port":  20000,
      "password": "密码",
      "up_mbps": 10,
      "down_mbps": 100,
      "tls": {
        "enabled": true,
        "server_name": "域名",
        "insecure": true,
        "alpn": [
          "h3"
        ]
      },
      "obfs": {
        "type": "salamander",
        "password": "密码"
      }
    },
```

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
sing-box不支持端口跳跃

**Comment by Fdulo** [comment]
> sing-box不支持端口跳跃。 你是想要生成随机端口号吗

十分感谢作者的回覆,因为我的不懂,导致浪费了一次round trip。其实想问的是原订阅在sing-box下发的配置hy2支持UDP输出 但转换后hy2不支持UDP了  

想知道项目的转换订阅怎么样可以默认让hy2可用UDP

我不确定是否有个人模板配置的影响
于是贴出配置
https://raw.githubusercontent.com/Fdulo/sing-box-fakeip/refs/heads/main/fakeip3.5.json


**不同的尝试与结果**
_原订阅生成与可用性_
 clash mate(应用)生成的出站有udp：ture与端口跳跃字眼但整个配置无法使用

NekoBox出站没有生成udp字眼但支持udp且TCP正常使用

Sing-box看不到配置但也支持了UDP与TCP正常使用

_模板生成_
用clash meta自已配置加上proxy-providers:生成与sing-box转换(本项目)配置
都除了不支持UDP都可以正常运作




**垃圾话(看不看没什么影响)**
我不懂代码与网络
因看到原订阅NekoBox魔改sing-box内核与clash meta(应用)都看到hy2出站有端口跳跃 但是clash meta有udp: true  又因不会看原订阅在sing-box生成的.bpf里面的配置 
却还是误做出了为端口跳跃 = udp启动这样子草率归纳 
虽然模糊认识udp是一种网络协议而hy2有端口跳跃这种功能，也确实没有在sing-box看到端口跳跃

**Comment by Fdulo** [comment]
我发现问题在端口不知道为什么当端口为0.0.0.0时udp就用不了了(抄配置抄的）

正常配置
```json
"http_proxy": {
          "enabled": true,
          "server": "127.0.0.1",
          "server_port": 7890
        }
      }
    },
    {
      "tag": "mixed",
      "type": "mixed",
      "listen": "127.0.0.1",
      "listen_port": 7890,
      "sniff": true
```

**Comment by Fdulo** [comment]
Sing-Box v1.11.0-beta.17 已支持端口跳跃
* [Sing-Box hysteria2文档部分](https://sing-box.sagernet.org/configuration/outbound/hysteria2/)
