### ISSUE TITLE
filter字段怎么使用

### ISSUE THREAD

**Issue by o88369** [Toperlock/sing-box-subscribe#116]
### 描述

{
    "subscribes": [
        {
            "url": "",
            "tag": "tag_1",
            "enabled": true,
            "emoji": 1,
            "subgroup": "gou",
            "prefix": "狗-",
            "User-Agent": "clashmeta"
        }

      {
        "tag":"HongKong",
        "type":"selector",
        "outbounds":[
          "{tag_1}"
        ],
        "filter":[
          {"action":"include","keywords":["🇭🇰|HK|hk|香港|港|HongKong"]}
        ]
      },
设置            "tag": "tag_1",然后配置文件outbounds，把all改成tag_1过滤不生效，没有节点，应该怎么设置。自建的vercel

用的是双订阅

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by o88369** [comment]
顺便问一下，providers.json的参数改成url的形式，这样比较方便多订阅链接

**Comment by Toperlock** [comment]
> 顺便问一下，providers.json的参数改成url的形式，这样比较方便多订阅链接

已经适配了“emoji”、“tag”、“ua”、“prefix”参数，但是它们不能分辨是哪个订阅，只能写死：让全部订阅链接的参数emoji、tag、ua、prefix都一致

**Comment by Toperlock** [comment]
![image](https://github.com/user-attachments/assets/23ecb242-f8ea-48bf-990f-3b33a5c737ef)
![image](https://github.com/user-attachments/assets/178695fa-d01d-41cb-812d-3d3673466f0c)
![image](https://github.com/user-attachments/assets/8a115b78-05a8-4a5c-b1c2-41b3b18915e4)
本地操作正常。
vercel测试也正常

订阅链接：https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/jd/refs/heads/main/new
模板：https://gist.githubusercontent.com/Toperlock/ed450e6f0f8eed2bd45cb19fa67ed790/raw/003ae83ea959919e1eb424a4971b940d9de33f6f/1.json

https://sing-box-subscribe-doraemon.vercel.app/config/https://mirror.ghproxy.com/https://raw.githubusercontent.com/gitbigg/jd/refs/heads/main/new&file=https://gist.githubusercontent.com/Toperlock/ed450e6f0f8eed2bd45cb19fa67ed790/raw/003ae83ea959919e1eb424a4971b940d9de33f6f/1.json

**Comment by o88369** [comment]
我大概明白是什么情况了，只要启用了"subgroup": "gou",
这个tag_1就不会生效。
我刚去测试了tag_1可以用

**Comment by o88369** [comment]
> > 顺便问一下，providers.json的参数改成url的形式，这样比较方便多订阅链接
> 
> 已经适配了“emoji”、“tag”、“ua”、“prefix”参数，但是它们不能分辨是哪个订阅，只能写死：让全部订阅链接的参数emoji、tag、ua、prefix都一致

要是url可以多订阅链接各参数可能会方便些，问题可以关闭了

**Comment by o88369** [comment]
感谢你的解答~！！
