### ISSUE TITLE
大佬您好，我修改代理地址没有效果，请问是哪里没修改对吗

### ISSUE THREAD

**Issue by chris6868** [Toperlock/sing-box-subscribe#117]
### 描述

您好大佬，我修改了sing-box-subscribe/config_template里面的https://mirror.ghproxy.com/ 为ghproxy.cn 后，生成的配置文件还是mirror.ghproxy.com，是我哪里没改对吗，还是还有其他地方也需要修改，感谢大佬。主要是mirror.ghproxy.com会重定向ghp.ci，ghp.ci挂了

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
用你搭建的vercel链接，生成配置选择你写好的ghproxy.cn配置文件

**Comment by chris6868** [comment]
> 用你搭建的vercel链接，生成配置选择你写好的ghproxy.cn配置文件

可能之前有缓存，我部署了一个新项目就好了，感谢大佬
