### ISSUE TITLE
关于转换时候默认User-Agent

### ISSUE THREAD

**Issue by libralv** [Toperlock/sing-box-subscribe#118]
### 描述

我本地docker搭建的后端然后搭配在shell里面用的sing-box使用默认转换的不带hhy2代理，但是我手动在网页打开ip:5000这个页面手动复制订阅链接把User-Agent改成clashmeta就可以生成带hy2的配置了，这个默认选项是否可以在转换时自己设置默认的选项

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
链接后面使用ua参数
![image](https://github.com/user-attachments/assets/8594ffba-b9de-4ab4-bdb6-e98338af6f58)

**Comment by Toperlock** [comment]
正常机场除了通过ua下发clash配置，应该还有自带可以在链接后面添加&flag=clashmeta吧

**Comment by libralv** [comment]
docker容器部署以后可否修改默认的ua并生成新镜像我想设置成打开ip：5000页面的ua为clashmeta

**Comment by Toperlock** [comment]
替换api/app.py里所有的`v2rayng`
![image](https://github.com/user-attachments/assets/13bcb851-3fc6-4f9e-b407-7666beff8cca)

**Comment by libralv** [comment]
好的我设置试试

**Comment by libralv** [comment]
已经成功修改
