### ISSUE TITLE
请求支持生成 h2 端口跳跃配置

### ISSUE THREAD

**Issue by Fdulo** [Toperlock/sing-box-subscribe#119]
### 描述

从 Sing-Box v1.11.0-beta.17 开始 sing-box 支持h2端口跳跃

* [ Sing-Box hysteria2 文档部分 ](https://sing-box.sagernet.org/configuration/outbound/hysteria2/)  

请问是否可以提供生成支持

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
弄好了

**Comment by Fdulo** [comment]
> 弄好了

**感谢更新!**
