### ISSUE TITLE
把订阅放在网址后面不能用

### ISSUE THREAD

**Issue by zqcnbi** [Toperlock/sing-box-subscribe#12]
![Screenshot_20231026_074708_io nekohasekai sfa_edit_342550472743564](https://github.com/Toperlock/sing-box-subscribe/assets/52245548/d2fa0d71-0809-4279-b539-f2bef5906a90)
安卓最新版本，浏览器能打开，

**Comment by Toperlock** [comment]
你试试把`https:/fjsk`改成`https://fjsk`

**Comment by zqcnbi** [comment]
还是不行，我先复制网页的

**Comment by zqcnbi** [comment]
> 你尝试把`https:/fjsk`改成`https://fjsk`，不行的话就先用本地形式，把内容复制粘贴

可以参考一下这个 感觉这个也挺好的，就是好久没更新了https://github.com/xmdhs/clash2sfa

**Comment by Toperlock** [comment]
> > 你尝试把`https:/fjsk`改成`https://fjsk`，不行的话就先用本地形式，把内容复制粘贴
> 
> 可以参考一下这个 感觉这个也挺好的，就是好久没更新了，并且只支持clash订阅https://github.com/xmdhs/clash2sfa

那他这个转换的订阅 sfa能下载下来吗

**Comment by Toperlock** [comment]
> 你试试把`https:/fjsk`改成`https://fjsk`，不行的话就先用本地形式，把内容复制黏贴

破案了，把`https:/fjsk`改成`https:///fjsk`

**Comment by Toperlock** [comment]
你订阅链接 https:/fjsk9.no-mad 里用了 `-`，导致singbox获取不到。你在浏览器直接打开订阅链接，把里面的内容复制到gist
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/d496ea28-7000-4251-b34f-df19c703d4b1)
用这个gist raw链接来进行转换
