### ISSUE TITLE
希望增加WeChat分流

### ISSUE THREAD

**Issue by luange** [Toperlock/sing-box-subscribe#14]
在使用后新加坡WeChat无法连接一直转圈，希望添加一个WeChat策略组

**Comment by Toperlock** [comment]
此为个人需求，只给你发配置模板自己操作

此模板加了 WeChat 分流与分组
[config_template_wechat_groups_tun.json](https://github.com/Toperlock/sing-box-subscribe/files/13194270/config_template_wechat_groups_tun.json)

![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/400cbdcf-949f-409d-b388-1e6395918792)

**Comment by luange** [comment]
该模板成功套上之后还是不能合作WeChat 日志最后放 ，使用全局直连或全局代理以及策略分流都是无法连接网络![image](https://github.com/Toperlock/sing-box-subscribe/assets/30614189/3e73b1b4-3e0b-4101-899d-bc88df3adbb7)

**Comment by Toperlock** [comment]
试试新的
[config_template_wechat_groups_tun.json](https://github.com/Toperlock/sing-box-subscribe/files/13276324/config_template_wechat_groups_tun.json)

<div align="left">
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/3a8517a2-e7a4-4492-a489-eab6e3ddd088" width="50%" />
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/18eea3d7-6f02-4f6f-8f99-2afe98a0fa35" width="50%" />
</div>
