### ISSUE TITLE
已经把链接地址修改为gist报错如下

### ISSUE THREAD

**Issue by pzb568** [Toperlock/sing-box-subscribe#15]
{
    "status": "error",
    "message_CN": "执行子进程时出错，获取链接内容超时，请尝试本地运行脚本或者把订阅链接内容放到gist; 你的订阅链接可能需要使用 越南 ip才能打开，很抱歉vercel做不到，请你把订阅链接里的node内容保存到gist里再尝试解析它。或者请你在本地运行脚本;",
    "message_VN": "Có lỗi khi thực hiện tiến trình con, vượt quá thời gian để lấy nội dung liên kết, vui lòng thử chạy kịch bản cục bộ hoặc đặt nội dung liên kết đăng ký vào Github Gist; Liên kết đăng ký của bạn có thể cần sử dụng IP Việt Nam để mở, xin lỗi Vercel không thể làm điều đó, vui lòng lưu nội dung nút trong liên kết đăng ký vào Github Gist trước khi cố gắng phân tích nó. Hoặc vui lòng chạy kịch bản cục bộ;",
    "message_EN": "Fetching the link content is timing out, please try running the script locally or putting the subscription link content into Github Gist; Your subscription link may need to use Vietnam ip to open, sorry Vercel can not do that, please save the node content in the subscription link to Github Gist before trying to parse it. Or please run the script locally;"
}

**Comment by Toperlock** [comment]
能把gist里的节点信息脱敏后，链接发给我看看吗。

**Comment by pzb568** [comment]
> 能把gist里的节点信息脱敏后，链接发给我看看吗。

https://gist.githubusercontent.com/pzb568/7091b63edb03be07438117ba02656dfe/raw/f96106090c6684c697e3e4e600a7932e4c0b0a85/gistfile1.txt

**Comment by Toperlock** [comment]
> > 能把gist里的节点信息脱敏后，链接发给我看看吗。
> 
> https://gist.githubusercontent.com/pzb568/7091b63edb03be07438117ba02656dfe/raw/f96106090c6684c697e3e4e600a7932e4c0b0a85/gistfile1.txt

<div align="left">
    <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/e8498821-b479-4b1d-8a3b-c5e164976994" width="30%" />
</div>

此链接在网页执行正常，你要不使用本地执行脚本，查看具体错误是什么

https://github.com/Toperlock/sing-box-subscribe#%E4%BA%8C%E6%9C%AC%E5%9C%B0%E5%AE%89%E8%A3%85
