### ISSUE TITLE
没有在此订阅下找到节点

### ISSUE THREAD

**Issue by Leaves672** [Toperlock/sing-box-subscribe#16]
没有在此订阅下找到节点，跳过
Không tìm thấy proxy trong link đăng ký này, bỏ qua
发现 🌌 Google 出站下的节点数量为 0 ，会导致sing-box无法运行，请检查config模板是否正确。
Sing-Box không chạy được vì không tìm thấy bất kỳ proxy nào trong outbound của 🌌 Google. Vui lòng kiểm tra xem mẫu cấu hình có đúng không!!
在使用之前下载的“sing-box-subscribe-main”是可以用的，今天看到有更新“sing-box-subscribe-no-flask-2.1.4”下载下来用是这个样子的，我尝试了运行“pip install requests paramiko scp chardet Flask PyYAML ruamel.yaml”，提示我要更新，我也输入了出现的更新的命令了

**Comment by Toperlock** [comment]
修了

**Comment by Leaves672** [comment]
没事了，谢谢
