### ISSUE TITLE
转换后的订阅，访问不了https://www.v2ex.com/?tab=hot，出现ERR_QUIC_PROTOCOL_ERROR这个报错，能请问下是哪里有错误吗

### ISSUE THREAD

**Issue by yanghl9898** [Toperlock/sing-box-subscribe#19]

**Comment by Toperlock** [comment]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/6efa78cd-42fa-49b8-9002-4e8ba70d8951)

走的是 !cn 这个策略组，看看是不是没选择节点导致走的direct。

要是走了节点还访问不了，请脱敏此节点的信息发给我。节点格式发clash的脱敏信息

**Comment by Toperlock** [comment]
[如何修复Chrome浏览器ERR_QUIC_PROTOCOL_ERROR报错](https://www.wbolt.com/err_quic_protocol_error.html)
