### ISSUE TITLE
可以取消自动为节点添加emoji功能吗

### ISSUE THREAD

**Issue by jklolixxs** [Toperlock/sing-box-subscribe#2]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/69113033/b5d84da3-cf58-47a6-a55f-750e972b0503)
如题，很多节点的国旗emoji已经乱了，可不可以取消这个功能，或者您告诉我，我删掉哪些代码可以关掉这个功能

**Comment by Toperlock** [comment]
每份协议解析的py文件里，node[tag] =tool.rename()，删掉tool.rename()只保留括号里的内容即可。

我明天修复bug

**Comment by Toperlock** [comment]
已更新tool.rename函数的错误

**Comment by Toperlock** [comment]
代码已重构，每份协议解析里去掉tag默认使用emoji的`tool.rename`函数。
改为`providers.json`文件里增加`emoji`标志，让用户决定是否对此条订阅添加国旗emoji
