### ISSUE TITLE
git加速代理需要更换

### ISSUE THREAD

**Issue by snakexgc** [Toperlock/sing-box-subscribe#20]
https://ghproxy.com/ 域名已经被GFW了，需要换用其它加速 

![image](https://github.com/Toperlock/sing-box-subscribe/assets/78722169/9c66f464-f264-4fcc-9f8a-97a4d2d80ccd) 

目前可以使用的域名是 https://gh.ghproxy.com/ 上图中 https://mirror.ghproxy.com/ 域名链接质量我测试比较一般！ 

可以考虑换用自建git加速站，利用cloudflare workers搭建即可。

**Comment by Toperlock** [comment]
group模板之前就改成 `testingcf.jsdelivr.net`, no_group模板现在改好了。
~~怎么会去用no_group模板呢~~

**Comment by snakexgc** [comment]
> group模板之前就改成 `testingcf.jsdelivr.net`, no_group模板现在改好了。 ~怎么会去用no_group模板呢~

因为我个人并不太需要分流，另外道个歉，之前改fork的时候不小心修改成您的仓库了，提交了个错误的信息😵，给您添麻烦了

**Comment by Toperlock** [comment]
fork后就是自己的仓库了，可以随便修改。只有提交pr才会影响上游仓库
