### ISSUE TITLE
在本地运行main.py时，无法读取--temp_json_data指定的json文件

### ISSUE THREAD

**Issue by leiyaocui** [Toperlock/sing-box-subscribe#21]
修正方法：
line 498 in main.py parse_json(): => return tool.readFile(value)

**Comment by Toperlock** [comment]
这是读取本地json模板文件的形式。
那为啥不按要求把temp_json_data放在config_template文件夹下
providers.json里的 `config_template` 参数在网页使用脚本用的

**Comment by leiyaocui** [comment]
我指的是读取本地json模板的parse_json函数与line 510 - line 513的处理逻辑之间存在矛盾，进而导致错误。

**Comment by Toperlock** [comment]
本地使用请你不要传入temp_json_data参数即可

tool.readFile(value)是读取本地文件，你有考虑在网页执行的时候怎么读取一条链接？

**Comment by leiyaocui** [comment]
你好像误解了我这里出现的问题，或许是我用line xxx的表述造成了你我之间信息传递的误差。

首先，我并没有在providers.json中填写config_template。

其次，我这里的出发点是，因为我希望在为不同的机场配置完成providers_xxx.json后，可以通过argparse来指定我要读取的特定的json而不是默认的那个，而我发现main.py中确实有这个argument，但是使用过程中发现它有点问题。

**Comment by Toperlock** [comment]
你发pr吧

**Comment by Toperlock** [comment]
你要是认真看reademe，不至于说出找不到指定配置json的方法

![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/eca41f93-629e-4e3a-8beb-19d1cd5a8195)
