### ISSUE TITLE
file参数优化

### ISSUE THREAD

**Issue by snakexgc** [Toperlock/sing-box-subscribe#22]
希望不只是能传入url，还能通过例如file=1来选中服务器中第一个配置文件，简化参数。

**Comment by Toperlock** [comment]
可以了

**Comment by snakexgc** [comment]
我在自己仓库中新建了更多的模板，当我file=2就会报错（我有四个模板），希望大佬增强一下健壮性吧，也就是统计一下服务器中有多少个模板，然后就可以输入相应的数（建议file=file+1，因为大部分情况我们说有几个模板都是从数字1开始的），另外就是对于输出的数超出了范围的，可以考虑使用默认的1号模板来增强健壮性。
大佬好高产啊！感谢大佬的辛勤开发维护！

**Comment by Toperlock** [comment]
好了

**Comment by snakexgc** [comment]
神中神！（打call！）
