### ISSUE TITLE
节点分组问题

### ISSUE THREAD

**Issue by zqcnbi** [Toperlock/sing-box-subscribe#23]
![Screenshot_20231110_160753](https://github.com/Toperlock/sing-box-subscribe/assets/52245548/3b8a132b-8dd4-4060-b499-7f87647078e5)
像谷歌 电报 推特 这些分组里面为什么不添加一个自动选择的选项呢

**Comment by zqcnbi** [comment]
假如说电报分组里面选择的节点不通了，还要手动选择，搞个自动选择选项感觉方便些

**Comment by Toperlock** [comment]
我个人不喜欢ip乱跑，你喜欢的话，可以按照格式修改模板，然后引用file参数。或者用自己搭vercel是弄

**Comment by zqcnbi** [comment]
好的
