### ISSUE TITLE
如何把sing-box自建的节点转换成订阅文件格式

### ISSUE THREAD

**Issue by debiansid** [Toperlock/sing-box-subscribe#3]
相当于这个的反向工作

**Comment by Toperlock** [comment]
singbox服务端建的节点，能生成uri链接吧，就是`vmess://` `tuic://`，这种开头的格式。
本地新建txt文件，粘贴你的uri格式节点信息(一行一条节点信息)，`providers.json`文件里，输入你的本地文件路径，解析即可。不需要弄成订阅的形式。[本地文件解析节点](https://github.com/Toperlock/sing-box-subscribe#providersjson%E6%96%87%E4%BB%B6)

**Comment by Toperlock** [comment]
还是说你想把生成的singbox完整的配置文件，弄成链接，能在sfa，sfi，tvos上导入远程订阅吗？
那就把你的singbox完整客户端配置文件，上传到服务器，比如gist上。gist是私密文件，别人找不到你的gist链接，除非你自己分享给别人看
