### ISSUE TITLE
报错 rule-set

### ISSUE THREAD

**Issue by adminidor** [Toperlock/sing-box-subscribe#30]
![999457](https://github.com/Toperlock/sing-box-subscribe/assets/1283711/290a02c3-5e65-4b74-b23c-550ece400b2a)

配置文件[config_template_groups_rule_set_tun.json](https://github.com/Toperlock/sing-box-subscribe/blob/main/config_template/config_template_groups_rule_set_tun.json)

**Comment by Toperlock** [comment]
rule set 是1.8.0的功能。请你更新singbox，或者请看readme写的，生成旧版配置

**Comment by adminidor** [comment]
> rule set 是1.8.0的功能。请你更新singbox，或者请看readme写的，生成旧版配置

旧版没问题，手机版是1.70的，没注意看
感谢
