### ISSUE TITLE
安卓客户端弹窗 ERROR  "parse outbound[25]:missing server_name or insecure=true

### ISSUE THREAD

**Issue by x19810000** [Toperlock/sing-box-subscribe#32]
debian系统安装的一键sing-box脚本，单条订阅是hysteria2://... ... 有hy2新协议，已修改 "User-Agent" 为：clashmeta   .sing-box 安卓客户端为1.8+ 

![屏幕截图 2023-12-18 132317](https://github.com/Toperlock/sing-box-subscribe/assets/36667391/3bb398df-88f6-4672-a7da-66c82a3abbaf)

**Comment by Toperlock** [comment]
题外话："User-Agent" 的作用适用在机场订阅，您要是填写URI，没必要写"User-Agent"
已修改，你再试试

**Comment by x19810000** [comment]
> 题外话："User-Agent" 的作用适用在机场订阅，您要是填写URI，没必要写"User-Agent" 已修改，你再试试

好的 感谢回复 另：
{
    "subscribes": [
        {
            "url": "URL LINK",
            "tag": "tag_1",
            "enabled": true,
            "emoji": 1,
            "prefix": "",
            "User-Agent": "v2rayng"
        },
        {
            "url": "URL LINK",
            "tag": "tag_2",
            "enabled": false,
            "emoji": 0,
            "prefix": "❤️",
            "User-Agent": "clashmeta"
上面的两个“URL LINK”都需要填写还是只填写tag1的就可以了？
除了填写URL-LINK之外别的都无需做修改是吗？

**Comment by Toperlock** [comment]
` "enabled": true`，才对填写的URL_LINK起作用

**Comment by x19810000** [comment]
> ` "enabled": true`，才对填写的URL_LINK起作用 每个参数都有它的作用：[参数说明](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#providersjson-file)

感谢回复！
按照指导已经不弹窗了，但是新问题出现了。
![photo_2023-12-18_15-11-24](https://github.com/Toperlock/sing-box-subscribe/assets/36667391/2fe703c7-fda7-4824-ab53-ec4dafb8b164)
log不停的试不停弹错。
无法连接上互联网。
不知道是我设置的问题还是我用的脚本的问题，sing-box是个新事物再加上我这个半瓶子。确实是挺蛋疼的。
再次感谢大佬。

**Comment by Toperlock** [comment]
> > ` "enabled": true`，才对填写的URL_LINK起作用 每个参数都有它的作用：[参数说明](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#providersjson-file)
> 
> 感谢回复！ 按照指导已经不弹窗了，但是新问题出现了。 ![photo_2023-12-18_15-11-24](https://private-user-images.githubusercontent.com/36667391/291178558-2fe703c7-fda7-4824-ab53-ec4dafb8b164.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODQ2OTMsIm5iZiI6MTcwMjg4NDM5MywicGF0aCI6Ii8zNjY2NzM5MS8yOTExNzg1NTgtMmZlNzAzYzctZmRhNy00ODI0LWFiNTMtZWM0ZGFmYjhiMTY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NWVhY2Y0Y2ExMDFkODVhZjhkZTBhZjk3NTE5OWZkZTUzZTIwNzliNjAzZmUwM2JiZjYxZGQ2ZGVlYThkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8viPKrTOpQNII9-vT-e9XagUwedE_2dfw0CiW9F-5HQ) log不停的试不停弹错。 无法连接上互联网。 不知道是我设置的问题还是我用的脚本的问题，sing-box是个新事物再加上我这个半瓶子。确实是挺蛋疼的。 再次感谢大佬。

你只是填写URI生成配置，singbox导入本地配置，没修改吗？
没修改的话，这个节点URI确定是正确能在clashmeta上ping通吗

**Comment by x19810000** [comment]
> > > ` "enabled": true`，才对填写的URL_LINK起作用 每个参数都有它的作用：[参数说明](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#providersjson-file)
> > 
> > 
> > 感谢回复！ 按照指导已经不弹窗了，但是新问题出现了。 ![photo_2023-12-18_15-11-24](https://private-user-images.githubusercontent.com/36667391/291178558-2fe703c7-fda7-4824-ab53-ec4dafb8b164.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4ODQ2OTMsIm5iZiI6MTcwMjg4NDM5MywicGF0aCI6Ii8zNjY2NzM5MS8yOTExNzg1NTgtMmZlNzAzYzctZmRhNy00ODI0LWFiNTMtZWM0ZGFmYjhiMTY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDA3MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NWVhY2Y0Y2ExMDFkODVhZjhkZTBhZjk3NTE5OWZkZTUzZTIwNzliNjAzZmUwM2JiZjYxZGQ2ZGVlYThkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8viPKrTOpQNII9-vT-e9XagUwedE_2dfw0CiW9F-5HQ) log不停的试不停弹错。 无法连接上互联网。 不知道是我设置的问题还是我用的脚本的问题，sing-box是个新事物再加上我这个半瓶子。确实是挺蛋疼的。 再次感谢大佬。
> 
> 你只是填写URI生成配置，singbox导入本地配置，没修改吗？ 没修改的话，这个节点URI确定是正确能在clashmeta上ping通吗
那么大佬 有时间简单的讲解一下怎么修改吗？
关键是我第一次导入本地设置成功过，后来脚本升级需要重装，再导入就无法联通了
需要做什么修改呢？

**Comment by Toperlock** [comment]
给出您的URI脱敏链接，关键地方用XXX代替

**Comment by x19810000** [comment]
> 给出您的URI脱敏链接，关键地方用XXX代替

hysteria2://31xxxx98-2xxe-4xxx-9xx7-6xxxxx92xxxb@:36370?peer=&insecure=0&sni=&alpn=h3#31319298-singbox_hysteria2

**Comment by Toperlock** [comment]
> > 给出您的URI脱敏链接，关键地方用XXX代替
> 
> hysteria2://31xxxx98-2xxe-4xxx-9xx7-6xxxxx92xxxb@:36370?peer=&insecure=0&sni=&alpn=h3#31319298-singbox_hysteria2

URI里缺少server信息@`server`:36370

生成的配置里你也可以代开看见缺少服务器ip/域名，这是一个不完整de的URI

![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/9dd1af46-c055-41a3-b9d9-45bf2519373e)

**Comment by x19810000** [comment]
> > > 给出您的URI脱敏链接，关键地方用XXX代替
> > 
> > 
> > hysteria2://31xxxx98-2xxe-4xxx-9xx7-6xxxxx92xxxb@:36370?peer=&insecure=0&sni=&alpn=h3#31319298-singbox_hysteria2
> 
> URI里缺少server信息@`server`:36370
> 
> 生成的配置里你也可以代开看见缺少服务器ip/域名，这是一个不完整de的URI
> 
> ![image](https://private-user-images.githubusercontent.com/86833913/291316755-9dd1af46-c055-41a3-b9d9-45bf2519373e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTE5OTksIm5iZiI6MTcwMjkxMTY5OSwicGF0aCI6Ii84NjgzMzkxMy8yOTEzMTY3NTUtOWRkMWFmNDYtYzA1NS00MWEzLWI5ZDktNDViZjI1MTkzNzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE1MDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwMDJkZTdjNmM3YjcyNzFlZmIwOWQ0MDkwNzgzMDQ0ZjJhYzg4Y2M1YWExMDc3ODA4MzNlNTU0ZmM3YzZlMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bq5B9s8xpz7_3U8I6poF_QErjRyPDhXl5dNjFsTndqA)

感谢大佬的耐心解答。问题果真就是这样的。
url不完整，是我脚本的问题。我手搓了一下ip地址上去可以了。
感谢
感谢
感谢！
