### ISSUE TITLE
json导入singbox如何更新订阅呢？

### ISSUE THREAD

**Issue by evilyao** [Toperlock/sing-box-subscribe#34]
如何更新订阅链接

**Comment by Toperlock** [comment]
[ReadME](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#feature)

**Comment by evilyao** [comment]
> [ReadME](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#feature)

用我蹩脚的英文和翻译器阅读了一遍。没看到哪里有更新订阅的地方。 请明示！

**Comment by Toperlock** [comment]
[视频演示](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#demo-video)

**Comment by Toperlock** [comment]
正好有人出了[教学视频](https://youtu.be/EBTuZuciv5Q)

**Comment by evilyao** [comment]
> [视频演示](https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#demo-video)

我了解这种更新，经过使用，它好像不会更新机场从新下发的节点内容。比如某机场一个节点为流量重置日期还剩5天。通过您的这总方式第二天更新后该节点还是剩余5天。 如果该节点直接用订阅链接更新就会变成4天。我不知道我又没有说清楚。

**Comment by evilyao** [comment]
> 正好有人出了[教学视频](https://youtu.be/EBTuZuciv5Q)

他的视频我看了一下就是口述了作者的wiki，不过添加自定义域名部分倒是挺好。不过这种更新方式它好像不会更新机场从新下发的节点内容。比如某机场一个节点为流量重置日期还剩5天。通过您的这总方式第二天更新后该节点还是剩余5天。 如果该节点直接用订阅链接更新就会变成4天。我不知道我又没有说清楚。

**Comment by Toperlock** [comment]
> > 正好有人出了[教学视频](https://youtu.be/EBTuZuciv5Q)
> 
> 他的视频我看了一下就是口述了作者的wiki，不过添加自定义域名部分倒是挺好。不过这种更新方式它好像不会更新机场从新下发的节点内容。比如某机场一个节点为流量重置日期还剩5天。通过您的这总方式第二天更新后该节点还是剩余5天。 如果该节点直接用订阅链接更新就会变成4天。我不知道我又没有说清楚。

https://xxxxxxx.vercel.app/config/url

这种格式不能符合你的要求吗?
用此格式就是能随时更新订阅转换成singbox内容，不能做到吗?
用此格式，只要你点击这个链接(触发网络请求的行为)，服务器vercel就是重新解析url订阅链接内容
怎么会像你说的得到的内容不是最新的

**Comment by evilyao** [comment]
> > > 正好有人出了[教学视频](https://youtu.be/EBTuZuciv5Q)
> > 
> > 他的视频我看了一下就是口述了作者的wiki，不过添加自定义域名部分倒是挺好。不过这种更新方式它好像不会更新机场从新下发的节点内容。比如某机场一个节点为流量重置日期还剩5天。通过您的这总方式第二天更新后该节点还是剩余5天。 如果该节点直接用订阅链接更新就会变成4天。我不知道我又没有说清楚。
> 
> https://xxxxxxx.vercel.app/config/url
> 
> 这种格式不能符合你的要求吗?
> 用此格式就是能随时更新订阅转换成singbox内容，不能做到吗?
> 用此格式，只要你点击这个链接(触发网络请求的行为)，服务器vercel就是重新解析url订阅链接内容
> 怎么会像你说的得到的内容不是最新的

![Screenshot_20240101_021714_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/564ce3a9-7a72-4faf-9473-e4b4bc53b3f6)

![Screenshot_20240101_021913_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/27189b6e-9508-4e47-a9f5-668901145932)

抱歉，我可能前面没讲清楚。单独添加一个订阅链接更新可以看到变化。

![Screenshot_20240101_022347_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/c63578da-8b45-4bc1-ba21-47c3e4ac3a8f)

这图是，我加入三个订阅链接通过gist把三个机场的节点转换成gistfile1.txt直连文件，再通过您方式转换，无论怎么更新都无法获得最新节点内容。

是否我的方法有问题？我一直觉得我这种把所有节点都转换出来再拿去转换成base64的方法很蠢，可是我一直找不到如何同时整合多个机场节点的方法。

**Comment by Toperlock** [comment]
哈哈哈哈因为你gist存的是＂那时获得的订阅内容＂这是固定的。
机场提供的订阅链接内容是实时改变的，所以你一直转换的是那个你获得的时间点的订阅内容。

目前 https://xxxxxxx.vercel.app/config/url 格式可以最多转换两个订阅链接(readme有写你应该会操作吧)
我晚点更新代码弄成能转换三个机场订阅

**Comment by evilyao** [comment]
> 哈哈哈哈因为你gist存的是＂那时获得的订阅内容＂这是固定的。 机场提供的订阅链接内容是实时改变的，所以你一直转换的是那个你获得的时间点的订阅内容。
> 
> 目前 https://xxxxxxx.vercel.app/config/url 格式可以最多转换两个订阅链接(readme有写你应该会操作吧) 我晚点更新代码弄成能转换三个机场订阅

哦，好的。等着你的更新呦，亲。  一直没睡等着你的回复

**Comment by evilyao** [comment]
> 哈哈，因为你的要点是“随后获得的订阅内容”是固定的。 机场提供的订阅链接内容是实时更改的，所以你一直转换的是你获得的时间点的订阅内容。
> 
> 目前https://xxxxxxx.vercel.app/config/url格式最多可以转换两个机场订阅链接(readme有写你应该会操作吧) 我晚点更新代码弄成能转换三个机场订阅

我刚看你更新了，试了一下放入3个订阅链接编码后导入1.8的singbox，出来的节点是前两个的订阅节点，第三个订阅节点没出来

**Comment by Toperlock** [comment]
https://sing-box-subscribe.vercel.app/config/https%3A%2F%2Fpastebin.com%2Fraw%2FxWWAYfeq%7Chttps%3A%2F%2Fmareep.netlify.app%2Fsub%2Fmerged_proxies_new.yaml%7Chttps%3A%2F%2Fgist.githubusercontent.com%2FToperlock%2Fb1ca381c32820e8c79669cbbd85b68ac%2Fraw%2Fdafae92fbe48ff36dae6e5172caa1cfd7914cda4%2Fgistfile1.txt

？？？

**Comment by Toperlock** [comment]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/357ed676-a93c-46e2-adeb-4ade366f49a4)

**Comment by evilyao** [comment]
> ![image](https://private-user-images.githubusercontent.com/86833913/293527934-357ed676-a93c-46e2-adeb-4ade366f49a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwNzYyNzAsIm5iZiI6MTcwNDA3NTk3MCwicGF0aCI6Ii84NjgzMzkxMy8yOTM1Mjc5MzQtMzU3ZWQ2NzYtYTkzYy00NmUyLWFkZWItNGFkZTM2NmY0OWE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDAyMjYxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNmJjNTFkNTY3ZDk1NzNkYmRhMzM4ZDY3NDAyMjY2YWRkNzU0ZThjMWM1Y2FjYmFkZGVhMGVjYzBlYjY0NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._2tfPSjCt0bMLPmKX80y9JcdK644qhFuzt514N2_oog)

![1](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/7ffd0870-ce2b-49ce-aa75-a87308972546)


我确实这样操作的。我还试着用了通用订阅链接不带clash的。第三条就是出不来

**Comment by evilyao** [comment]
> https://sing-box-subscribe.vercel.app/config/https%3A%2F%2Fpastebin.com%2Fraw%2FxWWAYfeq%7Chttps%3A%2F%2Fmareep.netlify.app%2Fsub%2Fmerged_proxies_new.yaml%7Chttps%3A%2F%2Fgist.githubusercontent.com%2FToperlock%2Fb1ca381c32820e8c79669cbbd85b68ac%2Fraw%2Fdafae92fbe48ff36dae6e5172caa1cfd7914cda4%2Fgistfile1.txt
> 
> ？？？

哦 我知道了。 可能是因为我是fork你的在我的vercel.com里操作的 还是老板没更新的。抱歉抱歉！

**Comment by evilyao** [comment]
![Screenshot_20240101_022347_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/4dc56ec6-f807-49c5-8252-7294e543463f)

![Screenshot_20240101_021913_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/fd24e890-5af4-47c3-9d57-3b3fcb66fe9b)

![Screenshot_20240101_021714_sing-box.jpg](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/0ed532d5-f7d6-40af-b710-180901b81049)

    完美了！居然还增加了支持添加参数。
