### ISSUE TITLE
最新的在线转换是不是又改回两条订阅了

### ISSUE THREAD

**Issue by evilyao** [Toperlock/sing-box-subscribe#41]
今天更新发现无法跟新成功，就从新转换了一下。加入3条订阅，客户端update后始终只有前两条订阅的节点。

**Comment by Toperlock** [comment]
自检第三条订阅链接能不能在网页打开，打开后有没有内容。有内容但是没转换的话，提供一下机场名

**Comment by evilyao** [comment]
没规律，我试着调换位置。有的时候少第三条，有的时候少第二条

**Comment by Toperlock** [comment]
你这三家机场名叫什么

**Comment by evilyao** [comment]
> 你这三家机场名叫什么

更换位置后每家都能显示出来，就是少一家。  火星联盟 三分机场 Mitce.com

**Comment by Toperlock** [comment]
那就是你的第二条的三分机场订阅不行吧

**Comment by evilyao** [comment]
还有个问题。同一个节点，从ip111.cn上看：小火箭从国外、从谷歌测试的ip都是相同的。（一直以来都是这样，用clash也是）

用singbox使用相同节点，从国外显示是该节点IP，从谷歌测试的ip是个香港的ip223.19.209.2不知道哪来的。

**Comment by evilyao** [comment]
> 那就是你的第二条的三分机场订阅不行吧

我把三分放第一位，第三为都能行的啊。 我每个订阅都放了不同的位置。好像就第二个位置不行

**Comment by evilyao** [comment]
> 那就是你的第二条的三分机场订阅不行吧

![微1](https://github.com/Toperlock/sing-box-subscribe/assets/22642892/99239e20-f0b3-479d-abd1-e688ebd40131)

放第三可以显示三分。第二位的mitce.com的 丢了

**Comment by Toperlock** [comment]
修了。
更新后再试试

**Comment by evilyao** [comment]
> 修了。 更新后再试试

我同步了。 好像还不行，确定还是丢第二个订阅。  节点连接后ip111.cn上看被封网站访问地址和节点地址不一致。

**Comment by Toperlock** [comment]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/7a344bea-dd1b-4098-b340-68245c3cb0ab)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/cc315f9e-2467-4282-91b2-f29faa8384e3)
叫named

**Comment by evilyao** [comment]
> ![image](https://private-user-images.githubusercontent.com/86833913/294741072-7a344bea-dd1b-4098-b340-68245c3cb0ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDgzMDksIm5iZiI6MTcwNDYwODAwOSwicGF0aCI6Ii84NjgzMzkxMy8yOTQ3NDEwNzItN2EzNDRiZWEtZGQxYi00MDk4LWIzNDAtNjgyNDVjM2NiMGFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2MTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YzU2ODZkYjNlYjMyMGE5MzI0NTU5ZjMxOTc3NTUyZTBiMmJlMDUzYWRkNzkyMWMxNzAzOGFlODk5NjdjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i4LGRPR2DH3J1LNKJ76t2GVPKNG2vtbfYa3237EUEU8) ![image](https://private-user-images.githubusercontent.com/86833913/294741080-cc315f9e-2467-4282-91b2-f29faa8384e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDgzMDksIm5iZiI6MTcwNDYwODAwOSwicGF0aCI6Ii84NjgzMzkxMy8yOTQ3NDEwODAtY2MzMTVmOWUtMjQ2Ny00MjgyLTkxYjItZjI5ZmFhODM4NGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA2MTMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhMjljN2Y0MjI1ODBmNDE0YmZlMWQ2MjBmZmZjZjFiNmM3NjQ2YTI2NDkwMDUxZjgwY2UyN2U1YTRlYWUzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sesZPlJaeWf1djBfwnm19XxiyOKC-P-SLve1ho8lct8) 叫named

Group里多了个命名/name的策略组 里面是第二个节点。  这是啥意思啊？

**Comment by evilyao** [comment]
转换后第二条叫named，而不是转换不成功 谷歌策略组走香港节点那当然是香港ip啊。你兜底proxy走的不是香港那当然测出来不一样啊 你怎么能想当然的以为检查网站必须走谷歌策略组

对，那个问题我删了，是我策略还原了。   第二个订阅不放在proxy里，单独的一个策略组怎么用呢？ 起什么作用

**Comment by evilyao** [comment]
auto里就是全的。  proxy里少第二个订阅 命名里是第二个。  有点乱

**Comment by Toperlock** [comment]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/054af89b-bb09-45d7-ae29-71f81e9ebff2)
改了
