### ISSUE TITLE
请问转换好订阅使用 Clash API 按照设置的端口连接连接不上是哪里没设置好啊？

### ISSUE THREAD

**Issue by OwO996** [Toperlock/sing-box-subscribe#43]
日志：
+0800 2024-01-12 15:58:49 [36mINFO[0m router: updated default interface 以太网, index 15
+0800 2024-01-12 15:58:49 [37mDEBUG[0m router: updating rule-set geoip-facebook from URL: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/facebook.srs
+0800 2024-01-12 15:58:49 [37mDEBUG[0m router: updating rule-set geoip-telegram from URL: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/telegram.srs
+0800 2024-01-12 15:58:49 [37mDEBUG[0m router: updating rule-set geosite-category-ads-all from URL: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/category-ads-all.srs
+0800 2024-01-12 15:58:49 [37mDEBUG[0m router: updating rule-set geoip-google from URL: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/google.srs
+0800 2024-01-12 15:58:49 [37mDEBUG[0m router: updating rule-set geosite-amazon from URL: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@sing/geo/geosite/amazon.srs
+0800 2024-01-12 15:58:49 [36mINFO[0m outbound/direct[direct]: outbound connection to testingcf.jsdelivr.net:443
+0800 2024-01-12 15:58:49 [36mINFO[0m outbound/direct[direct]: outbound connection to testingcf.jsdelivr.net:443
+0800 2024-01-12 15:58:49 [36mINFO[0m outbound/direct[direct]: outbound connection to testingcf.jsdelivr.net:443
+0800 2024-01-12 15:58:49 [36mINFO[0m outbound/direct[direct]: outbound connection to testingcf.jsdelivr.net:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup domain testingcf.jsdelivr.net
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup domain testingcf.jsdelivr.net
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup domain testingcf.jsdelivr.net
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: match[0] domain=[ghproxy.com cdn.jsdelivr.net testingcf.jsdelivr.net] => localDns
+0800 2024-01-12 15:58:49 [36mINFO[0m outbound/direct[direct]: outbound connection to testingcf.jsdelivr.net:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: match[0] domain=[ghproxy.com cdn.jsdelivr.net testingcf.jsdelivr.net] => localDns
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: match[0] domain=[ghproxy.com cdn.jsdelivr.net testingcf.jsdelivr.net] => localDns
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup domain testingcf.jsdelivr.net
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup domain testingcf.jsdelivr.net
+0800 2024-01-12 15:58:49 [37mDEBUG[0m outbound/direct[direct]: outbound connection to 223.5.5.5:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m outbound/direct[direct]: outbound connection to 223.5.5.5:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m outbound/direct[direct]: outbound connection to 223.5.5.5:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: match[0] domain=[ghproxy.com cdn.jsdelivr.net testingcf.jsdelivr.net] => localDns
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: match[0] domain=[ghproxy.com cdn.jsdelivr.net testingcf.jsdelivr.net] => localDns
+0800 2024-01-12 15:58:49 [37mDEBUG[0m outbound/direct[direct]: outbound connection to 223.5.5.5:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m outbound/direct[direct]: outbound connection to 223.5.5.5:443
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net NOERROR 1
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net CNAME testingcf.jsdelivr.net. 1 IN CNAME testingcf.jsdelivr.net.cdn.cloudflare.net.
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.85.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net NOERROR 1
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net NOERROR 1
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net NOERROR 1
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net CNAME testingcf.jsdelivr.net. 1 IN CNAME testingcf.jsdelivr.net.cdn.cloudflare.net.
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net CNAME testingcf.jsdelivr.net. 1 IN CNAME testingcf.jsdelivr.net.cdn.cloudflare.net.
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net CNAME testingcf.jsdelivr.net. 1 IN CNAME testingcf.jsdelivr.net.cdn.cloudflare.net.
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.85.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.85.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup succeed for testingcf.jsdelivr.net: 104.16.86.20 104.16.87.20 104.16.85.20 104.16.89.20 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.85.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup succeed for testingcf.jsdelivr.net: 104.16.88.20 104.16.86.20 104.16.87.20 104.16.85.20 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup succeed for testingcf.jsdelivr.net: 104.16.85.20 104.16.89.20 104.16.88.20 104.16.86.20 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup succeed for testingcf.jsdelivr.net: 104.16.87.20 104.16.85.20 104.16.89.20 104.16.88.20 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net NOERROR 1
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net CNAME testingcf.jsdelivr.net. 1 IN CNAME testingcf.jsdelivr.net.cdn.cloudflare.net.
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.89.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.88.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.86.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.87.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net A testingcf.jsdelivr.net.cdn.cloudflare.net. 1 IN A 104.16.85.20
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: exchanged testingcf.jsdelivr.net OPT OPT PSEUDOSECTION: EDNS: version 0 flags: MBZ: 0x0001, udp: 4096
+0800 2024-01-12 15:58:49 [37mDEBUG[0m dns: lookup succeed for testingcf.jsdelivr.net: 104.16.89.20 104.16.88.20 104.16.86.20 104.16.87.20 104.16.85.20
+0800 2024-01-12 15:58:59 [33mWARN[0m router: initialize rule-set take too much time to finish!

**Comment by Toperlock** [comment]
默认 127.0.0.1:9090

**Comment by OwO996** [comment]
> 默认 127.0.0.1:9090

我知道，我设置的是这个，我看过文档的，然后出这个问题了，运行之后 sing-box 本身也没翻墙的作用，不知道为啥，机场没问题的，Dler 的，节点配置我检查过，确定转换成功了。

**Comment by Toperlock** [comment]
+0800 2024-01-12 15:58:59 �[33mWARN�[0m router: initialize rule-set take too much time to finish!
下载规则集超时导致失败，yacd面板也有可能下载失败导致打不开clash api
"external_ui_download_detour": "direct" 把 direct改为你的dler里能正常使用的节点名
"download_detour": "direct" 也一样把direct改掉

**Comment by OwO996** [comment]
> +0800 2024-01-12 15:58:59 �[33mWARN�[0m router: initialize rule-set take too much time to finish! 下载规则集超时导致失败，yacd面板也有可能下载失败导致打不开clash api 先清理一下工作目录，按下面说的操作后重新下载： "external_ui_download_detour": "direct" 把 direct改为你的dler里能正常使用的节点名 "download_detour": "direct" 也一样把direct改掉

感谢亲的帮助，我去试试，麻烦亲啦。😘

**Comment by OwO996** [comment]
> +0800 2024-01-12 15:58:59 �[33mWARN�[0m router: initialize rule-set take too much time to finish! 下载规则集超时导致失败，yacd面板也有可能下载失败导致打不开clash api 先清理一下工作目录，按下面说的操作后重新下载： "external_ui_download_detour": "direct" 把 direct改为你的dler里能正常使用的节点名 "download_detour": "direct" 也一样把direct改掉

哇，大佬，真的能用了，谢谢你，爱死你了。^_^
