### ISSUE TITLE
请问可以支持docker部署吗？

### ISSUE THREAD

**Issue by songzhengpei** [Toperlock/sing-box-subscribe#46]
1.vercel虽然目前使用体验还不错，但是有几点不足，一个是自动同步经常会失效，各种各样的依赖错误失效之后就会发邮件提醒你也找不出来问题，只能重新部署。

2. 第2个是vercel仍然是国外的小流量服务器，不如docker方便。 docker在镜像更新，反代域名，国内直连，代码稳定性等等层面上都会更好呀。

3. 最后感谢大佬做出这么棒的项目，简洁清晰易懂。有效。谢谢

**Comment by Toperlock** [comment]
给你份文件自测。我设备因为一堆原因目前测试麻烦
目录结构：
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/e5f37c83-3c40-4e95-86a2-9274f3088f6d)


[demo.zip](https://github.com/Toperlock/sing-box-subscribe/files/13934884/demo.zip)

**Comment by songzhengpei** [comment]
谢谢, 提供一下反馈. 目前是在x86系统的Linux服务器docker搭建, 可以生成镜像,但是容器跑不起来, 处于不断重启的情况.

1. 下图, 上边两个镜像是我用你的源码dockerfile建的, 123是我自定义的容器名,不用介意..
<img width="430" alt="image" src="https://github.com/Toperlock/sing-box-subscribe/assets/96871072/1899420b-0ca3-4685-a12e-391a83d1ed9f">

2. 下图 是容器情况,采用的是bridge网络模式搭建, 可以看到不断重启,无法正常运行..
<img width="989" alt="image" src="https://github.com/Toperlock/sing-box-subscribe/assets/96871072/75a6b183-3ba5-477a-9e2f-b9d3d29daf6c">

3. 小弟才疏学浅,只会简单复制一下命令行, 我只能做到这里了, 再深的排查原因我不太会...也有可能是我的搭建命令出了错,这里我发出来给各位参考..
docker run -d --restart unless-stopped --privileged=true -p 7777:7777 --name singbox 123:singboxsub,,tips: 端口已打开,不是防火墙的问题.

最后详细叙述一下搭建过程...①首先是把大佬的demo源码复制到vps var/lib/docker/tmp路径,这个路径vps会提醒你. ②然后是自定义镜像的名称和tag标签,,③最后用以上的docker run命令生成容器. 结果是暂时不可用..等待更多大佬的反馈.谢谢

**Comment by Toperlock** [comment]
> 谢谢, 提供一下反馈. 目前是在x86系统的Linux服务器docker搭建, 可以生成镜像,但是容器跑不起来, 处于不断重启的情况.
> 
> 1. 下图, 上边两个镜像是我用你的源码dockerfile建的, 123是我自定义的容器名,不用介意..
> 
> <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/96871072/296721647-1899420b-0ca3-4685-a12e-391a83d1ed9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQwNDEsIm5iZiI6MTcwNTMxMzc0MSwicGF0aCI6Ii85Njg3MTA3Mi8yOTY3MjE2NDctMTg5OTQyMGItMGNhMy00Njg1LWExMmUtMzkxYTgzZDFlZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyN2JkMWYzOGQwZjVlNmJmOGNkN2NmMjVlNDM1ZGRmMmMzZjZhYmMzODE2ODJhYjA2MTU4MzMwZDc0NmRjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NjsDepUniQxz7FKkXyKOTvnBAD6QriXpKVqkBiSfxWs">
> 2. 下图 是容器情况,采用的是bridge网络模式搭建, 可以看到不断重启,无法正常运行..
> 
> <img alt="image" width="989" src="https://private-user-images.githubusercontent.com/96871072/296722031-75a6b183-3ba5-477a-9e2f-b9d3d29daf6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQwNDEsIm5iZiI6MTcwNTMxMzc0MSwicGF0aCI6Ii85Njg3MTA3Mi8yOTY3MjIwMzEtNzVhNmIxODMtM2JhNS00NzdhLTllMmYtYjlkM2QyOWRhZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDczZTg0ZDc4Njc5YTM5ZmQxMThlODZjM2FjODA0MjMyYTJlMjAzNzdiNGE1MDliOWZlYjdkZDkzYzZmOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpaMD3Fhb3Fqkwse1kW95yENw-vPGd2iOWt0y8KUpjA">
> 3. 小弟才疏学浅,只会简单复制一下命令行, 我只能做到这里了, 再深的排查原因我不太会...也有可能是我的搭建命令出了错,这里我发出来给各位参考..
>    docker run -d --restart unless-stopped --privileged=true -p 7777:7777 --name singbox 123:singboxsub,,tips: 端口已打开,不是防火墙的问题.
> 
> 最后详细叙述一下搭建过程...①首先是把大佬的demo源码复制到vps var/lib/docker/tmp路径,这个路径vps会提醒你. ②然后是自定义镜像的名称和tag标签,,③最后用以上的docker run命令生成容器. 结果是暂时不可用..等待更多大佬的反馈.谢谢


https://blog.csdn.net/u010381752/article/details/114364320

参考这篇再试试

**Comment by songzhengpei** [comment]
好的 我再试试

**Comment by songzhengpei** [comment]
> > 谢谢, 提供一下反馈. 目前是在x86系统的Linux服务器docker搭建, 可以生成镜像,但是容器跑不起来, 处于不断重启的情况.
> > 
> > 1. 下图, 上边两个镜像是我用你的源码dockerfile建的, 123是我自定义的容器名,不用介意..
> > 
> > <img alt="image" width="430" src="https://private-user-images.githubusercontent.com/96871072/296721647-1899420b-0ca3-4685-a12e-391a83d1ed9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQwNDEsIm5iZiI6MTcwNTMxMzc0MSwicGF0aCI6Ii85Njg3MTA3Mi8yOTY3MjE2NDctMTg5OTQyMGItMGNhMy00Njg1LWExMmUtMzkxYTgzZDFlZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyN2JkMWYzOGQwZjVlNmJmOGNkN2NmMjVlNDM1ZGRmMmMzZjZhYmMzODE2ODJhYjA2MTU4MzMwZDc0NmRjYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NjsDepUniQxz7FKkXyKOTvnBAD6QriXpKVqkBiSfxWs">
> > 2. 下图 是容器情况,采用的是bridge网络模式搭建, 可以看到不断重启,无法正常运行..
> > <img alt="image" width="989" src="https://private-user-images.githubusercontent.com/96871072/296722031-75a6b183-3ba5-477a-9e2f-b9d3d29daf6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQwNDEsIm5iZiI6MTcwNTMxMzc0MSwicGF0aCI6Ii85Njg3MTA3Mi8yOTY3MjIwMzEtNzVhNmIxODMtM2JhNS00NzdhLTllMmYtYjlkM2QyOWRhZjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDczZTg0ZDc4Njc5YTM5ZmQxMThlODZjM2FjODA0MjMyYTJlMjAzNzdiNGE1MDliOWZlYjdkZDkzYzZmOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpaMD3Fhb3Fqkwse1kW95yENw-vPGd2iOWt0y8KUpjA">
> > 3. 小弟才疏学浅,只会简单复制一下命令行, 我只能做到这里了, 再深的排查原因我不太会...也有可能是我的搭建命令出了错,这里我发出来给各位参考..
> >    docker run -d --restart unless-stopped --privileged=true -p 7777:7777 --name singbox 123:singboxsub,,tips: 端口已打开,不是防火墙的问题.
> > 最后详细叙述一下搭建过程...①首先是把大佬的demo源码复制到vps var/lib/docker/tmp路径,这个路径vps会提醒你. ②然后是自定义镜像的名称和tag标签,,③最后用以上的docker run命令生成容器. 结果是暂时不可用..等待更多大佬的反馈.谢谢
> 
> https://blog.csdn.net/u010381752/article/details/114364320
> 
> 参考这篇再试试

好的 我再试试

**Comment by Toperlock** [comment]
Dockerfile 内容改成这样试试
```Dockerfile
FROM python:3.9

COPY . /api
RUN \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ../requirements.txt

WORKDIR /api

CMD ["python", "app.py"]
```

**Comment by ohjunk2001** [comment]
@liununu 

可以啊，你这个我跑起来了

作者简化简化就能发布了

**Comment by Toperlock** [comment]
https://github.com/hestudy-blog/sing-box-subscribe-docker
