### ISSUE TITLE
如何屏蔽订阅节点里面的，不需要的节点。

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#47]
比如我这是一个混合格式。我想屏蔽掉里面的。vless。或者某个名字。

**Comment by Toperlock** [comment]
屏蔽协议
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/c442939c-1a0b-4b3e-9a8f-5679665a4923)
筛选节点
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/00a4c652-c294-411e-ac93-40252b4183b7)
