### ISSUE TITLE
如何增加非订阅节点

### ISSUE THREAD

**Issue by VirgilChen97** [Toperlock/sing-box-subscribe#48]
如题，没有订阅地址的自建节点或内网节点，如何和订阅节点一同生成到配置文件中呢？

**Comment by Toperlock** [comment]
可以填写节点URI
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/353e1870-9dd5-445c-9776-469adae56902)
也可以把节点URI都存在gist里当订阅链接转换
https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#-demonstration-video

**Comment by Toperlock** [comment]
现在sub-store也支持转换成singbox配置了
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/b1a7e93f-f2d4-4aae-abb1-757750d1b690)
