### ISSUE TITLE
用\n合并两条会报错  这样两个节点合并不对吗？

### ISSUE THREAD

**Issue by xznwwh** [Toperlock/sing-box-subscribe#49]
vless://7199f64c-4574-4245-8f0c-196906737295@surina.ns.cloudflare.com:2086/?type=ws&encryption=none&host=argo3.zznwwh.top&path=%2Fvless%3Fed%3D2048#vercel0-argo3\nvless://7199f64c-4574-4145-8f0c-196908737295@surina.ns.cloudflare.com:2086/?type=ws&encryption=none&host=argo8.xznwwh.top&path=%2Fvless%3Fed%3D2048#vercel-argo5

**Comment by Toperlock** [comment]
你要知道，'?', '&'符号在浏览器里视为标识符。你用明文URI会导致浏览器把内容给切割和内容打乱。
你这个只能在网页输入框里输入
在浏览器里请填写一个URI，或者多个常规的订阅链接
如果我要适配你这个写法，很拉低代码性能
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/3eae28a0-a9ec-4af3-bc74-9a9be5df3626)
你目前浏览器填两个URI，之后其他人就会想要在浏览器填5个URI，那样写很奇葩。
多个URI最好写在gist里，用gist链接来转换

**Comment by Toperlock** [comment]
你想要写在浏览器里需要base64编码
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/302b10fc-3ee4-4b86-b91b-e07a555b6e55)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/1d4d4bfc-e78c-43c4-aad4-ad468d84d80d)
