### ISSUE TITLE
修改请求UA

### ISSUE THREAD

**Issue by Xe0nRa0** [Toperlock/sing-box-subscribe#5]
部分订阅链接屏蔽了浏览器请求，会在请求订阅时返回特定网页导致无法获取订阅内容。修改请求UA为sing-box或Clash.Meta可以规避对浏览器请求的屏蔽，将请求伪装成由代理工具发出，正常获取订阅。

**Comment by Toperlock** [comment]
> 部分订阅链接屏蔽了浏览器请求，会在请求订阅时返回特定网页导致无法获取订阅内容。修改请求UA为sing-box或Clash.Meta可以规避对浏览器请求的屏蔽，将请求伪装成由代理工具发出，正常获取订阅。

已修改[#e1309f4](https://github.com/Toperlock/sing-box-subscribe/commit/e1309f455d42ff4775e7be9b445ab4cdcba2c384?diff=unified)

**Comment by Toperlock** [comment]
已添加”UA“参数，可以自定义UA。[commit 235b969](https://github.com/Toperlock/sing-box-subscribe/commit/235b969e6af2cb83aec7f0c70f1b0bb91f1ad6c7)

**Comment by onlyno999** [comment]
能不能够增加负载均衡。

**Comment by Toperlock** [comment]
> 能不能够增加负载均衡。

singbox没有负载均衡模式。你可以自行修改把urltest里的"tolerance"数值改的很大，相当于负载均衡

**Comment by onlyno999** [comment]
> > 能不能够增加负载均衡。
> 
> singbox没有负载均衡模式。你可以自行修改把urltest里的"tolerance"数值改的很大，相当于负载均衡

大佬，默认配置的规则是挺多的，如open AI规则里。希望增加手动选择节点，就完美了。一般机场啊，他不可能完美的去配置什么美国啊，台湾香港啊。那可能会用一些别的什么替代。

**Comment by onlyno999** [comment]
> > 能不能够增加负载均衡。
> 
> singbox没有负载均衡模式。你可以自行修改把urltest里的"tolerance"数值改的很大，相当于负载均衡

还有一个问题就是ipv6的节点，用最新的配置是没有网络的。
