### ISSUE TITLE
我又来了。

### ISSUE THREAD

**Issue by evilyao** [Toperlock/sing-box-subscribe#52]
今天更新了下，发现丢了两条订阅链接里的节点。重新转码了三个订阅，更新报错。 请问是不是更新了点啥？？

**Comment by Toperlock** [comment]
提供一下你怎么写的

**Comment by evilyao** [comment]
> 提供一下你怎么写的

https://sub.xxxxxx.cloudns.org/config/https%64位转换后的。转换每个连接之间用 | 隔开。

**Comment by Toperlock** [comment]
每个订阅都能在浏览器打开，并且有内容？

**Comment by evilyao** [comment]
肯定啦，咱们之前交流过。这次情况是singbox的自动更新，在没修改的情况下我发现节点少了，订阅还是以前的订阅链接。并且我发现少了以后，我还重新加了三条订阅去，重新64位编码再放进singbox里update，还是少两条。

**Comment by Toperlock** [comment]
那你解释为什么我的可以

**Comment by Toperlock** [comment]
就是订阅不行…………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………………

**Comment by evilyao** [comment]
两条编码后放在啊 config/后面 也出错。 只能不转化放一条。

**Comment by Toperlock** [comment]
你只能提供订阅链接给我看了，不然自己排错。https://t.me/h5683577
