### ISSUE TITLE
分流规则问题，目前dns依然100%泄露..

### ISSUE THREAD

**Issue by gowy222** [Toperlock/sing-box-subscribe#53]
### 描述

https://browserleaks.com/dns 测试下来，怎么都泄露，请问fakeipDNS模式 规则 如何正确配置. 
期望能改进默认配置模板。
openwrt的passwall2 fakeDNS模式完全不泄露。
chatGPT这种...必须DNS不泄露才能保住账号...

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
我仓库提供的配置没有问题。仓库没有提供fakeip配置，不是我的问题

https://github.com/Toperlock/sing-box-subscribe/assets/86833913/93d223e9-a5e4-4f6d-ab87-471bebc105a8

**Comment by gowy222** [comment]
@Toperlock 
谢，我是用openwrt tun + docker sing-box 跑的，再研究下亚托莉佬的配置看看

**Comment by Toperlock** [comment]
亚托莉佬的fakeip配置也没问题

https://github.com/Toperlock/sing-box-subscribe/assets/86833913/004f5e9a-38cb-43d3-8172-e5b2fdd68dce

**Comment by gowy222** [comment]
@Toperlock 
参考了多方配置。

目测可以了。
区别在于，proxy节点如果依赖自动 就会 泄露1个DNS，可能分流探测到了cn节点。手动限制固定节点目前99%不泄露(1%可能是机场问题。有些机场机没问题)。
满足正常使用。
