### ISSUE TITLE
三个订阅转换后还是丢后面两个

### ISSUE THREAD

**Issue by evilyao** [Toperlock/sing-box-subscribe#54]
### 描述

试了两天，怎么排放位置编码转换后都只能显示一个订阅中的节点。贴在浏览器打开也只有一个订阅的节点。使用你的订阅转换很久了，应该不是我操作错误的问题把。我用你的转换地址也试了一下，一样漏后面两个订阅节点。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
加群，找我私聊 https://t.me/zhangpeifu
