### ISSUE TITLE
可否在链接后增加新参数以自定义 `providers.json` 中的 `exclude_protocol`?

### ISSUE THREAD

**Issue by senzyo** [Toperlock/sing-box-subscribe#56]
### 描述

可否在链接后增加新参数以自定义 `providers.json` 中的 `exclude_protocol`?

就像 `emoji`, `tag`, `prefix`, `UA`, `file` 这些参数一样。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
只排除一个协议类型，还是多个

**Comment by senzyo** [comment]
希望可以排除多个协议类型，并覆盖 `exclude_protocol` 原有的 `ssr`。

**Comment by senzyo** [comment]
或者换个思路，不通过 `providers.json` 中的 `exclude_protocol` 筛选协议，而是在模板中筛选？比如：
```json
{
  "tag": "XXX",
  "type": "selector",
  "outbounds": ["{all}"],
  "filter": [
    {
      "action": "exclude",
      "protocol": ["ss|ssr"]
    }
  ]
}
```

**Comment by Toperlock** [comment]
参数弄好了，你试试 `&eps=vmess,hy2`

**Comment by senzyo** [comment]
很棒，一切正常，没发现问题
