### ISSUE TITLE
vercel生成的web parser是不是不能作为安卓订阅链接？

### ISSUE THREAD

**Issue by wyw1018** [Toperlock/sing-box-subscribe#57]
### 描述

用vercel 生成的web parser链接比如 https://vercel.xxxxx.cloudns.org/config/https://gist.githubusercontent.com/xxxx/607f253bb7671ec96ae24b910e563903/raw/c88fc9a86dce358730b23abdbc08f0b0a8892da3/providers.json&file=2 在网页中可以正常打开所有节点 配置。但是把此链接导入sing-box官方安卓端作为订阅链接更新后，并未获得providers.json里的订阅节点，只有自己在config.template里手动添加的节点。

是不是并不支持这样的链接作为订阅链接在官方安卓使用？

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
域名 vercel.xxxxx.cloudns.org 被墙。可以打开https://www.itdog.cn/tcping/ 测试能不能通
解决办法的话：换个域名或者只能先让singbox开代理，再去更新这个在线订阅

**Comment by wyw1018** [comment]
cloudns.org没有被墙，我用xxxx隐去了真实地址。
我再仔细读了使用说明，config/后面直接用clashmeta或者base64码订阅地址&file=xx即可。
我搞错了，我是把这些订阅地址放进了providers.json文件，再在gist里面生成providers.json文件的网址然后再放在config/后面，所以安卓更新订阅没有出现订阅节点。
