### ISSUE TITLE
hysteria节点转换后使用问题

### ISSUE THREAD

**Issue by fdy1993** [Toperlock/sing-box-subscribe#58]
### 描述

将机场的订阅连接通过这个项目本地运行后，转换出来的hysteria节点无法使用；使用机场提供的原始连接中hysteria节点是可以使用的。hysteria2使用是没这个问题，请问该如何解决

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
提供一下此项目生成的hysteria和机场的hysteria singbox节点信息。uuid等其他关键信息用*表示

**Comment by Toperlock** [comment]
试试最新的可不可以，添加了 `"insecure": false`

**Comment by fdy1993** [comment]
> 试试最新的可不可以，添加了 `"insecure": false`

非常感谢，刚刚试了最新提交的是可以使用了
