### ISSUE TITLE
vercel.app部署成功后，不能自动下载json文件

### ISSUE THREAD

**Issue by JogFeelingVI** [Toperlock/sing-box-subscribe#60]
### 描述

vercel.app 输出日志
[1;31m1、config_template_groups_rule_set_tun [0m[1;32m2、config_template_groups_rule_set_tun_fakeip [0m[1;33m3、config_template_groups_v6_rule_set_tun [0m[1;34m4、config_template_no_groups_tun_VN [0m
选择: [33mconfig_template_groups_rule_set_tun.json[0m
处理: [31mhttps://shenglue?clash=2&new=1[0m
文件不存在，正在保存：[33m./config.json[0m
保存配置文件时出错：[Errno 30] Read-only file system: './config.json'
文件不存在，正在保存：[33m/tmp/./config.json[0m
![截屏2024-03-08 09 56 02](https://github.com/Toperlock/sing-box-subscribe/assets/20158939/59a34f91-b6c1-4f8e-a98a-a35ced43d472)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by JogFeelingVI** [comment]
在你之前的https://sing-box-subscribe.vercel.app/,中可以正常下载转换后的json文件，是vercel.app 那里设置的不对吗

**Comment by Toperlock** [comment]
我没搞懂你说的话。
`文件不存在，正在保存：`这不是显示可以吗，vercel解析正常并保存中

**Comment by JogFeelingVI** [comment]
意思是怎么配置的，让他不要解析完后，直接开始下载，现在是解析完了之后，直接显示出来。

**Comment by Toperlock** [comment]
还是不懂你的意思。这个项目功能都没变化过，一直都是这样

**Comment by JogFeelingVI** [comment]
可以 之前的那个直接就是JSON 文件

**Comment by Toperlock** [comment]
https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#demo-video

https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#-demonstration-video

为什么我自己都不知道。我发的几个demo视频都是直接显示内容，从来没有json文件
