### ISSUE TITLE
使用Docker的本地问题

### ISSUE THREAD

**Issue by SakenW** [Toperlock/sing-box-subscribe#61]
### 描述

无法访问orbstack生成的本地域名，文档看了，不知道从何下手。

### 完整性要求

- [x] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [x] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by SakenW** [comment]
想问下这种情况订阅该如何改？

**Comment by SakenW** [comment]
auto_route
设置到 Tun 的默认路由。

为避免流量环回，请设置 route.auto_detect_interface 或 route.default_interface 或 outbound.bind_interface。

改了这个也可以了。

**Comment by SakenW** [comment]
auto_route
设置到 Tun 的默认路由。

为避免流量环回，请设置 route.auto_detect_interface 或 route.default_interface 或 outbound.bind_interface。

好像需要设置这个。

**Comment by Toperlock** [comment]
https://github.com/Toperlock/sing-box-subscribe/issues/46#issuecomment-1985566376

我没适配docker，试试这个
