### ISSUE TITLE
本地安装要如何自动运行

### ISSUE THREAD

**Issue by huang5307** [Toperlock/sing-box-subscribe#62]
### 描述

我是在本地安装，按照指示 `python main.py`，可以正常运行使用。但有一个问题很困扰我，就是这个运行每次都需要按一次enter来选择config模板，这样就没有办法自动执行了，我仔细看了说明，但没有发现有什么参数可以省掉这个按键，还请指导一下。
```
C:\sing-box\sing-box-subscribe>python main.py
1、config_template_groups_rule_set_tun 2、config_template_groups_rule_set_tun_fakeip 3、config_template_groups_v6_rule_set_tun 4、config_template_no_groups_tun_VN 5、config_template_toper_win_use
Nhập số để chọn mẫu cấu hình tương ứng (nhấn Enter để chọn mẫu cấu hình đầu tiên theo mặc định):
输入序号，载入对应config模板（直接回车默认选第一个配置模板）：
选择: config_template_groups_rule_set_tun.json
Mẫu cấu hình sử dụng: config_template_groups_rule_set_tun.json
```

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
在 `main.py` 里找到 `select_config_template()` 函数
直接指定 `uip = 1` 就是选择第一个模板
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/f1634c6b-c2bc-436f-a5c1-163b1c6b48e6)

**Comment by huang5307** [comment]
所以我执行的命令行 要写成 python main.py 1 还是  python main.py uip = 1 ？我试过 都是不行的，还是您的意思是要我自己改写程序？才能达到自动执行的条件？

**Comment by Toperlock** [comment]
> 所以我执行的命令行 要写成 python main.py 1 还是 python main.py uip = 1 ？我试过 都是不行的，还是您的意思是要我自己改写程序？才能达到自动执行的条件？

不是修改命令，是修改mian.py这个文件内容。

**Comment by Toperlock** [comment]
如果你不修改main.py文件内容，
执行命令：
`python main.py --template_index=0`
就是选择第一个模板

**Comment by huang5307** [comment]
> 如果你不修改main.py文件内容， 执行命令： `python main.py --template_index=0` 就是选择第一个模板

thanks!感谢了，这就是我想要的。

**Comment by Toperlock** [comment]
> > 如果你不修改main.py文件内容， 执行命令： `python main.py --template_index=0` 就是选择第一个模板
> 
> thanks!感谢了，这就是我想要的。 但是我试了在命令行执行 python main.py --template_index=0，还是会出现如下要求输入：
> 
> ```
> C:\sing-box\sing-box-subscribe>python main.py --template_index=0
> 1、config_template_groups_rule_set_tun 2、config_template_groups_rule_set_tun_fakeip 3、config_template_groups_v6_rule_set_tun 4、config_template_no_groups_tun_VN 5、config_template_toper_win_use
> Nhập số để chọn mẫu cấu hình tương ứng (nhấn Enter để chọn mẫu cấu hình đầu tiên theo mặc định):
> 输入序号，载入对应config模板（直接回车默认选第一个配置模板）：
> ```
> 
> PS：直接修改main.py的方式可以。

忘了说，releases里因为是 `no flask` 版本，没有 `template_index`参数。你直接下载这个项目解压运行
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/54b92633-bd12-474f-a96d-693a26b1c483)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/9fa8a485-c8a0-4a58-95ae-2a087c7e22ab)

**Comment by huang5307** [comment]
> > > 如果你不修改main.py文件内容， 执行命令： `python main.py --template_index=0` 就是选择第一个模板
> > 
> > 
> > thanks!感谢了，这就是我想要的。 但是我试了在命令行执行 python main.py --template_index=0，还是会出现如下要求输入：
> > ```
> > C:\sing-box\sing-box-subscribe>python main.py --template_index=0
> > 1、config_template_groups_rule_set_tun 2、config_template_groups_rule_set_tun_fakeip 3、config_template_groups_v6_rule_set_tun 4、config_template_no_groups_tun_VN 5、config_template_toper_win_use
> > Nhập số để chọn mẫu cấu hình tương ứng (nhấn Enter để chọn mẫu cấu hình đầu tiên theo mặc định):
> > 输入序号，载入对应config模板（直接回车默认选第一个配置模板）：
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > PS：直接修改main.py的方式可以。
> 
> 忘了说，releases里因为是 `no flask` 版本，没有 `template_index`参数。你直接下载这个项目解压运行 ![image](https://private-user-images.githubusercontent.com/86833913/314070866-54b92633-bd12-474f-a96d-693a26b1c483.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTUyMjMsIm5iZiI6MTcxMDg1NDkyMywicGF0aCI6Ii84NjgzMzkxMy8zMTQwNzA4NjYtNTRiOTI2MzMtYmQxMi00NzRmLWE5NmQtNjkzYTI2YjFjNDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTY4NWI4OTE4NmRkYTM1ZmZhMzgzYTc4ZDlmYWM4YzZhNGE3MDY4YjFlNzA0YTFhZTNlMjk2OGJlMjRlNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uoPMoNiaOGusjjyCPonZMgcRMfl0pOe6P0f-eLMGrY) ![image](https://private-user-images.githubusercontent.com/86833913/314071389-9fa8a485-c8a0-4a58-95ae-2a087c7e22ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NTUyMjMsIm5iZiI6MTcxMDg1NDkyMywicGF0aCI6Ii84NjgzMzkxMy8zMTQwNzEzODktOWZhOGE0ODUtYzhhMC00YTU4LTk1YWUtMmEwODdjN2UyMmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEzMjg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTJkYTFlYTlhNmFiNDQ2MTkxZTk4NGMxMDM4OTFlZmExY2U4MmJkM2JjMWZmOGQ0YzFlY2QxODgxYzU1M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GEHQ_TBWVWa1PfUOlxxLVSAiV6e8DMowk1CvxD67wzk)

ok，thanks
