### ISSUE TITLE
是否可以修改远程配置的模版，改用自己Fork后的模版

### ISSUE THREAD

**Issue by 7sasuke7l** [Toperlock/sing-box-subscribe#63]
### 描述

https://xxxxxxx.vercel.app/config/https://xxxxxxsubscribe?token=123456&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json
这是文档里给的替换链接，我想问的是
&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json
这部分，是指向原版这个库的配置模版，是否可以把整个File链接指向自己的Github仓库。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
可以的。

**Comment by 7sasuke7l** [comment]
还有一个问题，如果可以，是不是得复制2份sing-box subscribe项目，一份用来部署vercel，另一份单独修改json配置文件，然后用后者作为链接的file=之后的部分。
因为我试过，用同一份文件部署vercel和链接file=之后的引用，一直无法在客户端添加，但换成你的配置文件地址就可以正确添加。

**Comment by Toperlock** [comment]
不需要。部署vercel后，应该使用你自己的vercel网址，不需要&file=“远程模板链接” 就可以直接引用你自己仓库里的模板。但是可以引用 `&file=2` 来选你仓库里的第二个模板
我看了是因为你的json模板里有注释，导致程序读取json错误，还有缺少逗号的语法错误
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/8992dd0a-829c-4173-8892-e0aaa7111317)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/a2260ca4-e0c9-4bc0-8275-d61c644f0aea)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/c165e0b0-7fe3-44b2-b3a1-3a45804c4917)

请规范填写json格式

**Comment by 7sasuke7l** [comment]
感谢大佬，学到了学到了。
