### ISSUE TITLE
改进：能否考虑从机场导入节点时就排除一部分节点。

### ISSUE THREAD

**Issue by PullGuy** [Toperlock/sing-box-subscribe#64]
### 描述

我的机场里会有一些类似
{
      "tag": "套餐到期：长期有效"
 }
{
      "tag": "剩余流量：XXX GB"
}
这种的节点字段，但它是没用的，希望能提供一个exclude proxies字段以便在导入即可以排除。
虽然后面分组时可以筛选，但是每个分组里面都需要额外再写一遍排除字段，比较麻烦，也让模板配置文件显得冗长。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
你是要在 `provider.json` 文本填写 `expn` 这个参数？（此方法一我写好了）

<div align="left">
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/d1947d8a-bb16-437a-bdd9-7095b72a784c" 
width="50%" />
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/3438da9d-551e-4437-914f-06de3e015f79" 
width="50%" />
<img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/48d6ca55-6331-4ded-860b-8a66b74025bf" 
width="50%" />
</div>

~还是要远程链接添加参数：xxxxxxx.vercel.app/config/xxxxxxsubscribe?token=123456&expn=套餐,剩余~（此方法二我不想弄）

**Comment by CaoKang-David** [comment]
谢谢，方法一的更新我看到了，已经用上。
虽然你不想弄，但不妨碍我想要方法二。因为我需要生成一个链接以方便脚本自动更新配置文件，所以方法二更方便。/捂脸

**Comment by CaoKang-David** [comment]
天哪，简直神速！感谢！

**Comment by onlyno999** [comment]
非常实用。

**Comment by onlyno999** [comment]
> 方法二弄好了，用的`enn`参数，','分隔过滤关键词eg： `/config/URL_LINK&enn=网站,剩余流量`

排除某个节点都弄出来了。那为什么不指定用某个节点呢？一起搞

**Comment by CaoKang-David** [comment]
> 方法二弄好了，用的`enn`参数，','分隔过滤关键词 eg： `/config/URL_LINK&enn=网站,剩余流量`

非常抱歉，我最近发现用“|”分隔的多个链接，使用enn参数就没用了。我尝试了一下，发现只有一个链接的时候，这样做是没问题的。
盼望作者修复。

**Comment by Toperlock** [comment]
> > 方法二弄好了，用的`enn`参数，','分隔过滤关键词 eg： `/config/URL_LINK&enn=网站,剩余流量`
> 
> 非常抱歉，我最近发现用“|”分隔的多个链接，使用enn参数就没用了。我尝试了一下，发现只有一个链接的时候，这样做是没问题的。 盼望作者修复。

我测试两个订阅用“|”效果是正常的啊

**演示：**
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/e2855b35-04ae-4588-b723-3d9d863f4144)
**没过滤时：**
<div align="left">
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/68b994b8-dd99-4657-9680-66de09e9239f" alt="download" width="50%" />
</div>

**使用`enn`参数过滤“网站”“官网”**
<div align="left">
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/993259c6-3b96-4c6b-b3a2-2f430f6461aa" alt="download" width="50%" />
</div>

**Comment by Toperlock** [comment]
你会不会把`&enn=`参数也给 URLencode 了？

`/config/{URLencode:'URL1|URL2'}&enn=str1,str2`

**Comment by CaoKang-David** [comment]
![image](https://github.com/Toperlock/sing-box-subscribe/assets/19624728/279283ec-0ac3-41f6-a9bc-a63bdb82b48a)
我的订阅链接是这样的。
转换以后，里面仍然有这种节点。
![image](https://github.com/Toperlock/sing-box-subscribe/assets/19624728/0ae26df6-7629-484a-9045-04915c3140d9)

**Comment by Toperlock** [comment]
我规定的写法 `/config/URL&param` 不符合标准
正确的写法是：`/config/{URLencode: URL}?param1&param2&param3` // 不管是**1条**订阅链接还是2条、3条都需要URLencode，后面接“?”来传递参数，多个参数用“&”连接
得要修改代码为正确的URL写法才能满足你的要求，你的订阅链接都需要进行URL编码。
但是我懒，我不想要1条订阅时还得要去URL编码……
以下是修改好的 `app.py` ，把 `/config/<path:url>`路由内容替换下面内容即可
```python
@app.route('/config/<path:url>', methods=['GET'])
def config(url):
    user_agent = request.headers.get('User-Agent')
    rua_values = os.getenv('RUA')
    if rua_values and any(rua_value in user_agent for rua_value in rua_values.split(',')):
        return Response(json.dumps({'status': 'error', 'message': 'block'}, indent=4, ensure_ascii=False),
                        content_type='application/json; charset=utf-8', status=403)
    substrings = os.getenv('STR')
    if substrings and any(substring in url for substring in substrings.split(',')):
        return Response(json.dumps({'status': 'error', 'message_CN': '填写参数不符合规范'}, indent=4, ensure_ascii=False),
                        content_type='application/json; charset=utf-8', status=403)
    # temp_json_data_str = os.environ['TEMP_JSON_DATA']
    # temp_json_data = json.loads(temp_json_data_str)
    temp_json_data = json.loads('{"subscribes":[{"url":"URL","tag":"tag_1","enabled":true,"emoji":1,"subgroup":"","prefix":"","ex-node-name": "","User-Agent":"v2rayng"},{"url":"URL","tag":"tag_2","enabled":false,"emoji":1,"subgroup":"","prefix":"","ex-node-name": "","User-Agent":"v2rayng"},{"url":"URL","tag":"tag_3","enabled":false,"emoji":1,"subgroup":"","prefix":"","ex-node-name": "","User-Agent":"v2rayng"}],"auto_set_outbounds_dns":{"proxy":"","direct":""},"save_config_path":"./config.json","auto_backup":false,"exclude_protocol":"ssr","config_template":"","Only-nodes":false}')
    subscribe = temp_json_data['subscribes'][0]
    subscribe2 = temp_json_data['subscribes'][1]
    subscribe3 = temp_json_data['subscribes'][2]
    query_string = request.query_string.decode('utf-8')
    #print (f"query_string: {query_string}")
    #print (f"url: {url}")
    #encoded_url = quote(url, safe=':/')  # 对 url 进行编码
    encoded_url = unquote(url)
    #print (f"encoded_url: {encoded_url}")
    
    emoji_param = request.args.get('emoji', '')
    file_param = request.args.get('file', '')
    tag_param = request.args.get('tag', '')
    ua_param = request.args.get('ua', '')
    UA_param = request.args.get('UA', '')
    pre_param = request.args.get('prefix', '')
    eps_param = request.args.get('eps', '')
    enn_param = request.args.get('enn', '')

    if '/api/v4/projects/' in encoded_url:
        # 构建要删除的字符串列表
        params_to_remove = [
            f'&prefix={quote(pre_param)}',
            f'&ua={ua_param}',
            f'&UA={UA_param}',
            f'&file={file_param}',
            f'&emoji={emoji_param}',
            f'&tag={tag_param}',
            f'&eps={quote(eps_param)}',
            f'&enn={quote(enn_param)}'
        ]
        # 从query_string中删除这些字符串
        for param in params_to_remove:
            if param in query_string:
                query_string = query_string.replace(param, '')

        index_of_colon = encoded_url.find(":") + 2
        encoded_url = encoded_url[:index_of_colon-1] + "/" + encoded_url[index_of_colon-1:]
        parts = encoded_url.split('/api/v4/projects/')
        encoded_url = parts[0] + '/api/v4/projects/' + parts[1].replace('/', '%2F', 1) + "?" + query_string

    print (encoded_url)
    url_parts = encoded_url.split('|')
    if len(url_parts) > 1:
        subscribe['url'] = encoded_url.split('url=', 1)[-1].split('|')[0] if encoded_url.startswith('url') else encoded_url.split('|')[0]
        subscribe['ex-node-name'] = enn_param
        subscribe2['url'] = encoded_url.split('url=', 1)[-1].split('|')[1] if encoded_url.startswith('url') else encoded_url.split('|')[1]
        subscribe2['emoji'] = 1
        subscribe2['enabled'] = True
        subscribe2['subgroup'] = ''
        subscribe2['prefix'] = ''
        subscribe2['ex-node-name'] = enn_param
        subscribe2['User-Agent'] = 'v2rayng'
        if len(url_parts) == 3:
            subscribe3['url'] = encoded_url.split('url=', 1)[-1].split('|')[2] if encoded_url.startswith('url') else encoded_url.split('|')[2]
            subscribe3['enabled'] = True
            subscribe3['ex-node-name'] = enn_param
    if len(url_parts) == 1:
        subscribe['url'] = encoded_url.split('url=', 1)[-1] if encoded_url.startswith('url') else encoded_url
        subscribe['emoji'] = int(emoji_param) if emoji_param.isdigit() else subscribe.get('emoji', '')
        subscribe['tag'] = tag_param if tag_param else subscribe.get('tag', '')
        subscribe['prefix'] = pre_param if pre_param else subscribe.get('prefix', '')
        subscribe['ex-node-name'] = enn_param
        subscribe['User-Agent'] = ua_param if ua_param else 'v2rayng'
    temp_json_data['exclude_protocol'] = eps_param if eps_param else temp_json_data.get('exclude_protocol', '')
    temp_json_data['config_template'] = unquote(file_param) if file_param else temp_json_data.get('config_template', '')
    #print (f"Custom Page for {url} with link={full_url}, emoji={emoji_param}, file={file_param}, tag={tag_param}, UA={ua_param}, prefix={pre_param}")
    #page_content = f"生成的页面内容：{full_url}"
    #return page_content
    try:
        selected_template_index = '0'
        if file_param.isdigit():
            temp_json_data['config_template'] = ''
            selected_template_index = str(int(file_param) - 1)
        temp_json_data = json.dumps(json.dumps(temp_json_data, indent=4, ensure_ascii=False), indent=4, ensure_ascii=False)
        subprocess.check_call([sys.executable, 'main.py', '--template_index', selected_template_index, '--temp_json_data', temp_json_data])
        CONFIG_FILE_NAME = json.loads(os.environ['TEMP_JSON_DATA']).get("save_config_path", "config.json")
        if CONFIG_FILE_NAME.startswith("./"):
            CONFIG_FILE_NAME = CONFIG_FILE_NAME[2:]
        # 设置配置文件的完整路径
        config_file_path = os.path.join('/tmp/', CONFIG_FILE_NAME) 
        if not os.path.exists(config_file_path):
            config_file_path = CONFIG_FILE_NAME  # 使用相对于当前工作目录的路径 
        os.environ['TEMP_JSON_DATA'] = json.dumps(json.loads(data_json['TEMP_JSON_DATA']), indent=4, ensure_ascii=False)
        # 读取配置文件内容
        with open(config_file_path, 'r', encoding='utf-8') as config_file:
            config_content = config_file.read()
            if config_content:
                flash('配置文件生成成功', 'success')
                flash('Tạo file cấu hình thành công', 'Thành công^^')
        config_data = json.loads(config_content)
        return Response(config_content, content_type='text/plain; charset=utf-8')
    except subprocess.CalledProcessError as e:
        os.environ['TEMP_JSON_DATA'] = json.dumps(json.loads(data_json['TEMP_JSON_DATA']), indent=4, ensure_ascii=False)
        return Response(json.dumps({'status': 'error'}, indent=4,ensure_ascii=False), content_type='application/json; charset=utf-8', status=500)
        #return jsonify({'status': 'error', 'message': str(e)}) 
    except Exception as e:
        #flash(f'Error occurred while generating the configuration file: {str(e)}', 'error')
        return Response(json.dumps({'status': 'error', 'message_CN': '认真看刚刚的网页说明、github写的reademe文件;', 'message_VN': 'Quá thời gian phân tích đăng ký: Vui lòng kiểm tra xem liên kết đăng ký có chính xác không hoặc vui lòng chuyển sang "nogroupstemplate" và thử lại; Vui lòng không chỉnh sửa giá trị "tag", trừ khi bạn hiểu nó làm gì;', 'message_EN': 'Subscription parsing timeout: Please check if the subscription link is correct or please change to "no_groups_template" and try again; Please do not modify the "tag" value unless you understand what it does;'}, indent=4,ensure_ascii=False), content_type='application/json; charset=utf-8', status=500)
```

**Comment by PullGuy** [comment]
Thanks very much!
已经搞定！万分感谢

**Comment by onlyno999** [comment]
> 方法二弄好了，用的`enn`参数，','分隔过滤关键词 eg： `/config/URL_LINK&enn=网站,剩余流量`

如果订阅里面有VLESS ,VMESS，格式。用方法二只提取。VMESS用 这个方法二怎么又写？

**Comment by PullGuy** [comment]
好像又遇到了新的问题，在路由器里面更新订阅，在链接里面附加了排除掉一些节点的参数，如，enn=网站,地址,限速,剩余,过期,时间,有效,套餐,官址&ua=clashmeta&file=1。用浏览器打开链接就是正常的。生成的配置文件是正确的，但是路由器里面就不行。我尝试着用curl 链接的方式下载，发现粘贴地址到shell里面的时候，enn参数后面附带的汉字都没有被添加进去，形成的链接是这样子的： https://xxxxxx?enn=,,,,,,&ua=clashmeta。所以节点就没有被排除掉。这个有办法处理吗？

**Comment by PullGuy** [comment]
> 好像又遇到了新的问题，在路由器里面更新订阅，在链接里面附加了排除掉一些节点的参数，如，enn=网站,地址,限速,剩余,过期,时间,有效,套餐,官址&ua=clashmeta&file=1。用浏览器打开链接就是正常的。生成的配置文件是正确的，但是路由器里面就不行。我尝试着用curl 链接的方式下载，发现粘贴地址到shell里面的时候，enn参数后面附带的汉字都没有被添加进去，形成的链接是这样子的： [https://xxxxxx?enn=,,,,,,&ua=clashmeta。所以节点就没有被排除掉。这个有办法处理吗？](https://xxxxxx?enn=,,,,,,&ua=clashmeta%E3%80%82%E6%89%80%E4%BB%A5%E8%8A%82%E7%82%B9%E5%B0%B1%E6%B2%A1%E6%9C%89%E8%A2%AB%E6%8E%92%E9%99%A4%E6%8E%89%E3%80%82%E8%BF%99%E4%B8%AA%E6%9C%89%E5%8A%9E%E6%B3%95%E5%A4%84%E7%90%86%E5%90%97%EF%BC%9F)

我现在临时的解决办法是在app.py文件中，将要排除节点的关键字直接赋值给了enn_param变量，如enn_param = '网站,地址,限速,剩余,过期,时间,有效,套餐'

**Comment by Toperlock** [comment]
把`网站,地址,限速,剩余,过期,时间,有效,套餐,官址`进行[URL encode](https://www.urlencoder.org/)
![image](https://github.com/user-attachments/assets/0db6854c-9834-40a0-a2ad-70bdf108490f)

**Comment by onlyno999** [comment]
> 把`网站,地址,限速,剩余,过期,时间,有效,套餐,官址`进行[URL编码](https://www.urlencoder.org/) ![图像](https://private-user-images.githubusercontent.com/86833913/363501935-0db6854c-9834-40a0-a2ad-70bdf108490f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjUxNTYsIm5iZiI6MTcyNTI2NDg1NiwicGF0aCI6Ii84NjgzMzkxMy8zNjM1MDE5MzUtMGRiNjg1NGMtOTgzNC00MGEwLWEyYWQtNzBiZGYxMDg0OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA4MTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZDE2MzFiYTYzYmNkMzVjZTUzNTIxMTJjYzdmNWYwYjMyMjY0Mzc5NzA5ZTNlYmNhMTU2YzEyZWZkNDA5MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZtM58l9eETUtcWTiGD0Ta5kVnjrtgIsYROUtn83KTI)

所以呢，大佬直接弄一个允许某协议，厄准只准某节点，其它的通通排除不就行了。

**Comment by PullGuy** [comment]
> 把`网站,地址,限速,剩余,过期,时间,有效,套餐,官址`进行[URL encode](https://www.urlencoder.org/) ![image](https://private-user-images.githubusercontent.com/86833913/363501935-0db6854c-9834-40a0-a2ad-70bdf108490f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzk0NDcsIm5iZiI6MTcyNTMzOTE0NywicGF0aCI6Ii84NjgzMzkxMy8zNjM1MDE5MzUtMGRiNjg1NGMtOTgzNC00MGEwLWEyYWQtNzBiZGYxMDg0OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjZhNjNmNzc4MzY5ODkwODg0NDhhNDQzNWVhZWY5YTU5ZjcyZjQwOThjZjcxNDMzNjk0YWFjOTI2YWI3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bLM0cN62ah4vUH_euqpBgNQKH5L8qfissdQDg0pgud

**Comment by PullGuy** [comment]
> 把`网站,地址,限速,剩余,过期,时间,有效,套餐,官址`进行[URL encode](https://www.urlencoder.org/) ![image](https://private-user-images.githubusercontent.com/86833913/363501935-0db6854c-9834-40a0-a2ad-70bdf108490f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzk0NDcsIm5iZiI6MTcyNTMzOTE0NywicGF0aCI6Ii84NjgzMzkxMy8zNjM1MDE5MzUtMGRiNjg1NGMtOTgzNC00MGEwLWEyYWQtNzBiZGYxMDg0OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDA0NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZjZhNjNmNzc4MzY5ODkwODg0NDhhNDQzNWVhZWY5YTU5ZjcyZjQwOThjZjcxNDMzNjk0YWFjOTI2YWI3MmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bLM0cN62ah4vUH_euqpBgNQKH5L8qfissdQDg0pgudo)

感谢，问题解决了。
