### ISSUE TITLE
Unable to deploy the project to the vercel

### ISSUE THREAD

**Issue by nickctsang** [Toperlock/sing-box-subscribe#65]
### 描述

Hi,

I got the following error when I trying to deploy this project to the vercel. Could you please tak a look?

`17:22:15.021 | Running build in Washington, D.C., USA (East) – iad1
-- | --
17:22:15.258 | Cloning github.com/nickctsang/sing-box-subscribe (Branch: main, Commit: b31412c)
17:22:15.286 | Skipping build cache, deployment was triggered without cache.
17:22:16.345 | Cloning completed: 1.085s
17:22:17.010 | Running "vercel build"
17:22:18.297 | Vercel CLI 33.6.1
17:22:18.753 | Error: Unable to find any supported Python versions.
17:22:18.753 | Learn More: http://vercel.link/python-version`

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
Check if the Pipfile file is missing from the project.
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/0424f706-3515-4068-9cd3-50dce797a9fc)

**Comment by nickctsang** [comment]
Hi,

As checked, this file is appear in my repositories but it won't work.

**Comment by Toperlock** [comment]
Did you follow the tutorial steps?
https://github.com/Toperlock/sing-box-subscribe/blob/main/docs/vercel-en.md

**Comment by nickctsang** [comment]
Hi,

I beleive I have already followered your guide to deploy the project to vercel and I did again after receieving your reply, but it still won't work.

**Comment by Toperlock** [comment]
The Framework Preset choose Other. You can find it in Settings > General > Node.js Version.
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/497394d3-c981-492c-9516-7d7d6cabea4e)

**Comment by nickctsang** [comment]
FYI.

![image](https://github.com/Toperlock/sing-box-subscribe/assets/165006940/a30023b1-78b5-4fb8-9f20-31194c13dc3d)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/165006940/4039fa1c-8ea7-44d6-ae4b-403e1b5f70bb)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/165006940/a9375bd1-698f-4411-8b3f-681947e2d0a9)

**Comment by Toperlock** [comment]
maybe try: https://github.com/vercel/vercel/discussions/11128
If that doesn't work either, sorry I can't help you either

**Comment by nickctsang** [comment]
Hi,

Thanks for your help. It work now. 

Many thanks!!!!

**Comment by TaoRone** [comment]
Thank you for your attempt and answer upstairs. Now I will translate the solution in Chinese.
vercel的问题，经测试，当vercel导入失败时，进入项目，设置，常规，修改node.js为18.x即可
这个问题应该最近会被vercel修复

**Comment by jpcchu** [comment]
> 谢谢楼上的尝试和回答。现在我将这个解决方案翻译成中文。 vercel的问题，经过测试，当vercel导入失败时，进入项目，应该设置，常规，修改node.js为18.x即可 这个问题最近会被vercel修复

thank you very much for your help
