### ISSUE TITLE
关于纯V6节点，订阅转换后不支持

### ISSUE THREAD

**Issue by TaoRone** [Toperlock/sing-box-subscribe#67]
### 描述

首先谢谢大佬的付出，clash直接转换过来很舒服，接一个短链接就可以实现自定义sing-box订阅
不过我发现一个问题，大佬的规则中默认仅仅对IPV4设置了相应规则
如果我先将纯V6节点先订阅转换为clash，此时clash可以通；而如果此时再通过大佬的项目转换，则V6节点不同
看了看安卓端日志报错，error的日志都提示 入站 tun 模式访问地址连接被拒绝

请教大佬有没有解决办法？

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
tun需要添加ipv6
`"inet6_address": "fdfe:dcba:9876::1/126",`
选择 ipv6 模板：
[config_template_groups_v6_rule_set_tun.json](https://github.com/Toperlock/sing-box-subscribe/blob/main/config_template/config_template_groups_v6_rule_set_tun.json)

**Comment by TaoRone** [comment]
> tun需要添加ipv6 `"inet6_address": "fdfe:dcba:9876::1/126",` 选择 ipv6 模板： [config_template_groups_v6_rule_set_tun.json](https://github.com/Toperlock/sing-box-subscribe/blob/main/config_template/config_template_groups_v6_rule_set_tun.json)

感谢大大的回复，v6问题解决！
给与后来者经验：

单链接：
`sing-box-subscribe转换链接/config/ + 原clash或其他订阅  + &file= + 代理github链接 + https://github.com/Toperlock/sing-box-subscribe/blob/main/config_template/config_template_groups_v6_rule_set_tun.json`

双链接|多链接：
`sing-box-subscribe转换链接/config/ + URL编码（原clash或其他订阅 + | + 第二个订阅） + &file=+ 代理github链接 + https://github.com/Toperlock/sing-box-subscribe/blob/main/config_template/config_template_groups_v6_rule_set_tun.json`
