### ISSUE TITLE
使用https://xxxxxxx.vercel.app/config/+订阅地址的方式，是否支持多个订阅地址分别加tag的形式

### ISSUE THREAD

**Issue by nfervor** [Toperlock/sing-box-subscribe#68]
### 描述

使用下面订阅地址加tag的方式时，尝试了多次 url&tag=one|url2&tag=two 使用使用url encode后，抓取到的节点信息是 | 之前的节点信息和tag。
这种方式是否不支持多个tag。
谢谢。
https://xxxxxxx.vercel.app/config/https://xxxxxxsubscribe?token=123456&tag=one&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json

![image](https://github.com/Toperlock/sing-box-subscribe/assets/11471720/90d5ddb8-0938-46ce-80d9-8b2e6818ff0d)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
不行。目前用这种远程链接解析的所有参数只能共用。不然代码写起来很臃肿

**Comment by Toperlock** [comment]
可以使用 sub-store 来生成singbox配置，它还能让你进行复杂的操作
https://t.me/zhetengsha/1070

**Comment by nfervor** [comment]
好的，那我再看substore。感谢
