### ISSUE TITLE
新模版遇到点问题

### ISSUE THREAD

**Issue by GGoukebo** [Toperlock/sing-box-subscribe#69]
### 描述

如果节点全部属于others，HongKong、Taiwan下的出站默认走的direct，以前是proxy，导致现在的Google、Twitter必须要手动指定others才可以，这个可以优化一下吗？

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
你试试现在怎么样

**Comment by GGoukebo** [comment]
OK
