### ISSUE TITLE
clash.meta订阅

### ISSUE THREAD

**Issue by ldh1983** [Toperlock/sing-box-subscribe#7]
我用的机场订阅链接，只有在支持clash.meta订阅的网络工具里才可以刷出hy等新协议节点，在其它工具只能刷出ss等老协议节点。您的这个工具好像也只能刷出老协议的节点。可否优化一下，让这类订阅链接刷出全部节点。

**Comment by Toperlock** [comment]
#5 
修改User-Agent，https://github.com/Toperlock/sing-box-subscribe#providersjson%E6%96%87%E4%BB%B6

**Comment by ldh1983** [comment]
网页版能不能用自己的模板？如果用自己的模板，跟随上游跟新后自己的模板是不是会被上游的模板覆盖？谢谢。

**Comment by Toperlock** [comment]
> 网页版能不能用自己的模板？如果用自己的模板，跟随上游跟新后自己的模板是不是会被上游的模板覆盖？谢谢。

可以用自己的模板，merge合并分支，不会覆盖
