### ISSUE TITLE
我希望默认DNS是国外的而不是国内的，有配置项可以修改吗？

### ISSUE THREAD

**Issue by Idealisten** [Toperlock/sing-box-subscribe#70]
### 描述

我希望默认DNS是国外的而不是国内的，有配置项可以修改吗？

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
请修改自己的模板，改为 `"final": "proxyDns",` 或直接删掉 `"final": "localDns",`。
最后用你自己的vercel链接生产配置，不要用我的。
若你想继续用 subscribe-doraemon.vercel.app，你就用file参数使用你自己模板（使用方法请认真看reademe文档）
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/55f5d670-d1ac-412a-84c2-c441bcb3c3b8)
