### ISSUE TITLE
能否讲一下怎么设置链式代理？

### ISSUE THREAD

**Issue by zwl1619** [Toperlock/sing-box-subscribe#72]
能否讲一下怎么设置链式代理？
比如客户端在中国大陆，中转机在香港，落地机在美国，
那么，三者分别怎么配置？

**Comment by Toperlock** [comment]
落地机节点信息添加`detour: 中转机`
此项目不支持添加detour。sub-store可以做到你要需求
https://t.me/zhetengsha/1241

**Comment by xingmiye** [comment]
> 落地机节点信息添加`detour: 中转机` 此项目不支持添加detour。sub-store可以做到你要需求 https://t.me/zhetengsha/1241

尝试使用sub-store配置失败。

请问作者大大，按照以下方法，是否可以实现呢？

再次分析需求，落地机如果是自建，那么节点配置信息不会改变，比如落地机的自建节点是ss1，可以直接把该自建节点ss1写入到我们项目的订阅地址【&file=】后面的config_template.json的配置模板里面。比如机场速度不错，但是不能解锁奈飞，而落地机可以解锁，所以机场节点可作为中转机，然后配置模板相关内容如下：

```
  "outbounds": [
    {
      "tag": "🚀 节点选择",
      "type":"selector",
      "outbounds":[
        "♻️ 自动选择",
        "🚀 手动切换",
        "luodi"
      ],
      "default": "luodi"
    },
    {
      "tag": "🚀 手动切换",
      "type":"selector",
      "outbounds":[
        "{all}"     \\经过本项目，机场节点会被添加到这里作为中转机节点
      ]
    },
    {
      "tag": "♻️ 自动选择",
      "type": "urltest",
      "outbounds":[
        "{all}"     \\经过本项目，机场节点会被添加到这里自动测速
      ],
      "url": "http://www.gstatic.com/generate_204",
      "interval": "10m",
      "tolerance": 50
    },
    {
      "tag": "luodi",
      "type": "shadowsocks",
      "server": "落地机ip",
      "server_port": 1080,    \\端口自定义
      "network": "udp",
      "method": "ss的加密方法",
      "password": "密码",
      "detour": "🚀 手动切换"     \\在手动切换组中，自行选择某个机场节点作为中转机节点
    }
  ]
```

通过以上配置即可实现单个自建落地机的链式代理配置需求

如果有多个自建落地机节点，也只能参考以上方式，自行写在【&file=】后面的config_template.json的配置模板的出站里面作为单独已配置好的出站，并且把节点名字写在【"tag": "🚀 节点选择"】里面，不能包含在【/config/URL】的【URL】中。

强调：【🚀 节点选择】和【🚀 手动切换】是不一样的组，且【🚀 手动切换】不能包含落地机相关配置，否则sing-box会报错启动失败

**Comment by Toperlock** [comment]
> 分析需求，落地机如果是自建，那么节点配置信息不会改变，比如落地机的自建节点是ss1，可以直接把该自建节点ss1写入到我们项目的订阅地址【&file=】后面的config_template.json的配置模板里面。比如机场速度不错，但是不能解锁奈飞，而落地机可以解锁，所以机场节点可作为中转机，然后配置模板相关内容如下：

直接在配置文件里写好"detour"不是更快吗，有什么情况是需要脚本来操作的？
