### ISSUE TITLE
请问我的机场提供singbox订阅链接，可以把多个singbox订阅链接合并吗，提取出来节点用自己的规则

### ISSUE THREAD

**Issue by 11215548** [Toperlock/sing-box-subscribe#77]

**Comment by Toperlock** [comment]
网页可填写多个订阅
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/320d3636-d0aa-4828-860a-e0f4f75b4e30)

请你看一下readme内容，有文字、又有举例、又有图片、又有视频，怎么会看不懂呢。readme都写了方法，谢谢

https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#feature

**Comment by Toperlock** [comment]
或者你可能想要的是这个功能：在网页里有个参数`Only-nodes`
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/e09c4ac2-5056-4eb7-897b-e41c0a8c2983)
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/23e8db7d-8027-4456-89d9-18c4f3b1c044)

**Comment by 11215548** [comment]
谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个
`https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json`
不翻墙就下不了

**Comment by 11215548** [comment]
> 谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个 `https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json` 不翻墙就下不了，翻墙了就能下

还想问下大佬，这样的网址也能添加多个订阅链接吗

**Comment by Toperlock** [comment]
> 谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个 `https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json` 不翻墙就下不了

![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/c2373d69-fd9a-426b-ad26-825ca568c4b6)

**Comment by Toperlock** [comment]
> > 谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个 `https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json` 不翻墙就下不了，翻墙了就能下
> 
> 还想问下大佬，这样的网址也能添加多个订阅链接吗

![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/434c1bf5-310a-48ce-a56b-f359eecfbeda)

**Comment by 11215548** [comment]
> > > 谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个 `https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json` 不翻墙就下不了，翻墙了就能下
> > 
> > 
> > 还想问下大佬，这样的网址也能添加多个订阅链接吗
> 
> ![image](https://private-user-images.githubusercontent.com/86833913/333789351-434c1bf5-310a-48ce-a56b-f359eecfbeda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzEzMTIsIm5iZiI6MTcxNjYzMTAxMiwicGF0aCI6Ii84NjgzMzkxMy8zMzM3ODkzNTEtNDM0YzFiZjUtMzEwYS00OGNlLWE1NmItZjM1OWVlY2ZiZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA5NTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjQ0MDY5MmU1MTI1NTM4ZTc0ZTMwOGUzZWU4NTY0YjY1NThjMTc2NGVjYTg4Yjg2NDUwNjM1OTgzOGYzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bl8anD24grDtX_63psuA60NIzdgH6cWpusWS5s4nGIU)

看到了，这个最多就3个吗 ，我后来fork了项目，改里面的index.html和providers.json文件，想把
![image](https://github.com/Toperlock/sing-box-subscribe/assets/169347597/479690c2-c94e-449f-a11f-49e82aa1bff4)
这里面的默认配置直接改好，这样就可以直接用域名+`/generate_config`的方式生成配置文件，但是好像改了之后再重新部署还是显示原来的

**Comment by Toperlock** [comment]
> > > > 谢谢，我现在按教程也fork了项目，在vercel部署了。用你教程说的订阅链接可以下载能用的`json`文件，不翻墙就下不了文件，是不是`vercel`的项目要翻墙才能访问。用的链接是这个 `https://我的项目名字.vercel.app/config/我的机场sing-box订阅链接&ua=clashmeta&file=https://github.com/Toperlock/sing-box-subscribe/raw/main/config_template/config_template_groups_rule_set_tun.json` 不翻墙就下不了，翻墙了就能下
> > > 
> > > 
> > > 还想问下大佬，这样的网址也能添加多个订阅链接吗
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/86833913/333789351-434c1bf5-310a-48ce-a56b-f359eecfbeda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzEzMTIsIm5iZiI6MTcxNjYzMTAxMiwicGF0aCI6Ii84NjgzMzkxMy8zMzM3ODkzNTEtNDM0YzFiZjUtMzEwYS00OGNlLWE1NmItZjM1OWVlY2ZiZWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDA5NTY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjQ0MDY5MmU1MTI1NTM4ZTc0ZTMwOGUzZWU4NTY0YjY1NThjMTc2NGVjYTg4Yjg2NDUwNjM1OTgzOGYzYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bl8anD24grDtX_63psuA60NIzdgH6cWpusWS5s4nGIU)
> 
> 看到了，这个最多就3个吗 ，我后来fork了项目，改里面的index.html和providers.json文件，想把 ![image](https://private-user-images.githubusercontent.com/169347597/333790983-479690c2-c94e-449f-a11f-49e82aa1bff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2MzM0NTUsIm5iZiI6MTcxNjYzMzE1NSwicGF0aCI6Ii8xNjkzNDc1OTcvMzMzNzkwOTgzLTQ3OTY5MGMyLWM5NGUtNDQ5Zi1hMTFmLTQ5ZTgyYWExYmZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMDMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmU1NmU0ZmNiY2VmZjYwMjU1NDdlNWNjZDljMjgxZjEwNDU3NjBjY2FkNWZjYzNjOWU4YjFkM2M1YmU4NTA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1k12bi31M5N3h8jIjsCRiyd8yN2znCO_c6_F9TbvFo0) 这里面的默认配置直接改好，这样就可以直接用域名+`/generate_config`的方式生成配置文件，但是好像改了之后再重新部署还是显示原来的

链接形式最多3个。
/api/app.py 也得改
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/4c3fba48-514d-4b4b-b409-154873a83f30)
