### ISSUE TITLE
对于多个要转换的文件，其中一个若发生错误直接跳过并进行下一步，而不是只要其中一个文件转换错误就退出执行了

### ISSUE THREAD

**Issue by zypluckyphoenix** [Toperlock/sing-box-subscribe#79]
### 描述

![image](https://github.com/Toperlock/sing-box-subscribe/assets/98106970/c119e59c-55bb-49c0-be2a-ac5dd190280e)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
> ### 描述
> ![image](https://private-user-images.githubusercontent.com/98106970/337861433-c119e59c-55bb-49c0-be2a-ac5dd190280e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NDQ5NDYsIm5iZiI6MTcxNzg0NDY0NiwicGF0aCI6Ii85ODEwNjk3MC8zMzc4NjE0MzMtYzExOWU1OWMtNTViYi00OWMwLWJlMmEtYWM1ZGQxOTAyODBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDExMDQwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMGM2OWI3MGY1MDBlMzliOThiMGU4NWVjNTY3OWNhYWI1ZDU2ODk4ZmNmYjBkNDU3NGQyNzA1ZWZhMzEyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lxW1K86RYDaXsmapr1yh9TSKd6VGjFusq3idvBiIEfE)
> 
> ### 完整性要求
> * [x]  我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
> * [x]  我保证转换的订阅链接可以在浏览器打开，并且有内容。

你试着在这添加异常处理：
```python
def parse_content(content):
    # firstline = tool.firstLine(content)
    # # print(firstline)
    # if not get_parser(firstline):
    #     return None
    nodelist = []
    for t in content.splitlines():
        t = t.strip()
        if len(t) == 0:
            continue
        factory = get_parser(t)
        if not factory:
            continue
        try:
            node = factory(t)
        except Exception as e:
            pass
        if node:
            nodelist.append(node)
    return nodelist
```
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/858aa894-58ac-417d-a65b-236039e22e8b)

**Comment by PullGuy** [comment]
发生错误的位置不一样。我这个是在这一段出现的错误，我不太敢改，怕改乱了。
![image](https://github.com/user-attachments/assets/7b4b2eb7-a8f9-4a3d-8774-d3563e9c0e5c)
