### ISSUE TITLE
不支持本地Hysteria2链接

### ISSUE THREAD

**Issue by kj54321** [Toperlock/sing-box-subscribe#8]
RT
问题复现：
1. 创建本地文件 local.txt
`cat local.txt 
hysteria2://123@[xxxx:xxxx:xxxx:3::4c]:443/?insecure=1&sni=mydomain`

2. 编辑 providers.json
`cat providers.json 
{
    "subscribes":[
        {
            "url": "./local.txt",
            "tag": "机场1",
            "enabled": true,
            "emoji": 1,
            "prefix": ""
        },
        {
            "url": "./local2.txt",
            "tag": "机场2",
            "enabled": false,
            "emoji": 0,
            "prefix": "❤️机场前缀 - "
        }
    ],
    "auto_set_outbounds_dns":{
        "proxy": "",
        "direct": ""
    },
    "save_config_path": "./config.json",
    "auto_backup": false,
    "exlude_protocol":"",
    "User-Agent":""
}
`

3. 运行 main.py
`python3 main.py
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
1、config_template_groups_tun 2、config_template_no_groups_tun 3、config_template_tun 4、config_template_tun_2 
输入序号，载入对应config模板（直接回车默认选第一个配置模板）：1
处理./local.txt
发现 🌌 Google 出站下的节点数量为 0 ，会导致sing-box无法运行，请检查config模板是否正确。
Traceback (most recent call last):
  File "/home/kj54321/Downloads/sing-box-subscribe/main.py", line 420, in <module>
    final_config = combin_to_config(config,nodes)
  File "/home/kj54321/Downloads/sing-box-subscribe/main.py", line 340, in combin_to_config
    config_path = json.loads(temp_json_data).get("save_config_path", "config.json")
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

**Comment by Toperlock** [comment]
请选择`no_groups`模板。因为`config_template_groups_tun`模板里面有分组筛选节点名称，分组没筛选到节点会报错。
`hysteria2://123@[xxxx:xxxx:xxxx:3::4c]:443/?insecure=1&sni=mydomain`转换效果见图二
<div align="left">
    <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/85ef9405-5494-49cb-a3e4-64d41994b2f5" alt="install" width="60%" />
    <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/31eb2b88-36e9-42e0-8881-6aa9d04ace36" alt="install" width="60%" />
</div>

**Comment by kj54321** [comment]
谢谢，暂时只能模板2
