### ISSUE TITLE
新更新的模板出现错误。需清理缓存

### ISSUE THREAD

**Issue by Teda9** [Toperlock/sing-box-subscribe#81]
### 描述

![image](https://github.com/Toperlock/sing-box-subscribe/assets/133856115/c7f70dab-b850-4e00-a7c3-f872cb41f589)
我是用vercel部署的，启用的自动更新，在之前一直用得没问题，昨天随着项目更新了新的模板，就启动失败了， 失败提示如上。

一直用的是config/URL 形式使用的， 在后面加上 &file=1 和 &file=2 都是有这个提示， 用 &file=3 就能正常启动了。
恰好看到更新的是 12两个模板， 3的模板是5个月前的。
比较确定是新的模板设置有bug ， 麻烦帮忙查看一下。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
#31

**Comment by Toperlock** [comment]
<div align="left">
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/305d2eb3-1020-49b2-a23f-b2bf55078336" width="30%" />
  <img src="https://github.com/Toperlock/sing-box-subscribe/assets/86833913/4b941f01-03e9-47cc-806c-935a22f9437e" width="30%" />
</div>

奇怪我一切正常，你清理缓存再试试

**Comment by Teda9** [comment]
清除缓存之后，确实可以连接成功了。 感谢。

**Comment by Van426326** [comment]
相同的报错   清sing-box缓存确实解决了
