### ISSUE TITLE
关于节点的扩展配置

### ISSUE THREAD

**Issue by KurobaYuuki** [Toperlock/sing-box-subscribe#82]
### 描述

从订阅获取到的节点配置中含有UoT、多路径TCP、UDP分段等扩展内容，但经过转换后这些内容全部丢失，是否考虑增加相关转换方法？
转换前：
![转换前](https://github.com/Toperlock/sing-box-subscribe/assets/78408086/2b02bcf8-819e-4729-91bf-96ff3f6e5cbd)
转换后：
![转换后](https://github.com/Toperlock/sing-box-subscribe/assets/78408086/db6bf45b-6b5f-4c8d-bfbf-60f4cb91aa1a)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
这个订阅是clash格式吗

**Comment by KurobaYuuki** [comment]
> 这个订阅是clash格式吗

你提醒我了，我去了解了一下，我使用的订阅链接是可以根据请求的 UA 下发不同类型的配置文件的。
上面[转换前](https://private-user-images.githubusercontent.com/78408086/345395600-2b02bcf8-819e-4729-91bf-96ff3f6e5cbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDg3NjEsIm5iZiI6MTcyMDAwODQ2MSwicGF0aCI6Ii83ODQwODA4Ni8zNDUzOTU2MDAtMmIwMmJjZjgtODE5ZS00NzI5LTkxYmYtOTZmZjNmNmU1Y2JkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ODBhY2I2NzVjNDZmZWFjYjZiMDZjZjVlZWEwY2YzZGFjMTA0NzZiYjNhZTIzMTdjOGY0NjFjYzMwN2JhNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cpqTWqzN5LTWS5bCOIiMx4R9g6eTw6gQjOR9e-XPCEc)的图片是 UA 为 singbox 时的原始配置，[转换后](https://private-user-images.githubusercontent.com/78408086/345395745-db6bf45b-6b5f-4c8d-bfbf-60f4cb91aa1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMDg3NjEsIm5iZiI6MTcyMDAwODQ2MSwicGF0aCI6Ii83ODQwODA4Ni8zNDUzOTU3NDUtZGI2YmY0NWItNmI1Zi00YzhkLWJmYmYtNjBmNGNiOTFhYTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDEyMDc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NTNhYWE0YjI2ZmU1NzEzY2YxYWRjNDkwZTlhNmYwMzIwZThiZDFjMGQwOGYyYmQ2ODNmYTI0MWY3OGE4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZRpC7nYYbrKgIcyXWxl4Q7eR9Do5m2nfhOGXQTnuBFs)的图片是 UA 为 clashmeta 时用下发的配置转换成 singbox 格式造成的。
若是用 singbox 格式来转换，不会造成上述 UoT、多路径TCP、UDP分段的配置丢失。
但实际上将 clash 格式转换成 singbox 格式时确实会造成 udp、UoT 配置丢失。
以下为 clash 格式的原始配置：
![图片](https://github.com/Toperlock/sing-box-subscribe/assets/78408086/8b208ade-effb-43de-92a1-9e93b302d4a6)

**Comment by Toperlock** [comment]
clash文档里也就只有 udp-over-tcp 字段，我就添加这个就行了吧
![image](https://github.com/Toperlock/sing-box-subscribe/assets/86833913/097bac5b-93cc-44e6-b784-07bc2483c70e)

**Comment by KurobaYuuki** [comment]
是的，麻烦了

**Comment by Toperlock** [comment]
测试一下 [872d16b](https://github.com/Toperlock/sing-box-subscribe/commit/872d16bc9dca128241c9aedc7dd04348dfabb3dc)
