### ISSUE TITLE
parsers/clash2base64.py 的 wireguard 部分的修改建议

### ISSUE THREAD

**Issue by thuhollow2** [Toperlock/sing-box-subscribe#85]
### 描述

主流的代理软件如 [v2rayNG](https://github.com/2dust/v2rayNG/blob/master/V2rayNG/app/src/main/kotlin/com/v2ray/ang/util/fmt/WireguardFmt.kt) 采用 wiregard:// 作为协议名，并省去了 pre-share-key，将 ip 和 ipv6 变量合并为 address，对应 [parsers/clash2base64.py](https://github.com/Toperlock/sing-box-subscribe/blob/main/parsers/clash2base64.py#L297-L305) 可修改为

```
link = "wireguard://{privateKey}@{server}:{port}?publickey={publicKey}&address={ip}&mtu={mtu}&reserved={reserved}#{name}".format(**warp_info)
```

和

```
link = "wireguard://{privateKey}@{server}:{port}?publickey={publicKey}&address={ip}&mtu={mtu}#{name}".format(**warp_info)
```

以下为 v2rayN 配置示例

<img width="666" alt="屏幕截图_20240716_145906" src="https://github.com/user-attachments/assets/b88eb535-1d54-4d4b-8f36-b70682e7cc43">

```
wireguard://ePOa21YJ51AWpSh4uY%2BrwxekiOHZEVKIh78RgYOJ0Fo%3D@wa.bachebiapain.ir:890/?publickey=bmXOC%2BF1FxEMF9dyiK2H5%2F1SUtzH0JuVo51h2wPfgyo%3D&address=172.16.0.2%2C2606%3A4700%3A110%3A8f81%3Ad551%3Aa0%3A532e%3Aa2b3&mtu=1280#NiREvil%E2%81%B0%E2%81%B7%C2%A0%C2%A0%2Bplus
```

除 parsers/wg.py 外建议增加 wireguard:// 的解析，[tool.py](https://github.com/Toperlock/sing-box-subscribe/blob/main/tool.py#L217-L219) 取消 wg:// 和 wireguard:// 的合并。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
我这解析结果不是一样吗，只少了一个mtu
![image](https://github.com/user-attachments/assets/cd7289ee-1fa4-43f0-9eb6-aa0c86d69cf7)
![image](https://github.com/user-attachments/assets/6bae7880-ea5f-4cca-8af8-a3dc87b18ea7)
![image](https://github.com/user-attachments/assets/b37ba5a7-0d38-40d0-aeba-b15c07d17536)

**Comment by thuhollow2** [comment]
不好意思，没有检查 parsers/wg.py 是否修改，我fork的还没更新
不过感觉 parsers/clash2base64.py 用 wireguard:// 做 url 前缀或许更通用一些
