### ISSUE TITLE
作者你好，网页端的默认 `providers.json` 信息需要在哪里修改？我直接修改 `providers.json` 并没有生效

### ISSUE THREAD

**Issue by FaithAluten** [Toperlock/sing-box-subscribe#86]
### 描述

- 部署方式：docker
- 问题：修改 docker 内部的 `providers.json` 并没有改变网页端 `Edit TEMP_JSON_DATA` 下的 `providers.json` 默认信息

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by FaithAluten** [comment]
顺便想问一下，直链订阅的方式，`https://<我的域名>/config/<我的订阅>&file=<配置文件>` 中的 `<配置文件>` 必须是直链当中包含模版信息么，我在服务端已经写好了几个模版，请问可不可以直接调用呢

**Comment by Toperlock** [comment]
`providers.json`内容不会显示在网页上。网页只显示默认值，避免敏感数据被人看到。
编辑`providers.json`的行为，适合在本地运行 `python mian.py`

可以调用你写好的配置模板，配置模板要求：

https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#config-template-files

![image](https://github.com/user-attachments/assets/bf22ff1d-b3f4-452f-9418-c53552455779)

**Comment by Toperlock** [comment]
网页 `Edit TEMP_JSON_DATA`方框内容修改是一次性的，**生成配置后会自动还原为默认值**（避免敏感数据被人看到，**如果你修改后没点击生成配置是不会还原的**）

**Comment by FaithAluten** [comment]
> `providers.json`内容不会显示在网页上。网页只显示默认值，避免敏感数据被人看到。 编辑`providers.json`的行为，适合在本地运行 `python mian.py`
> 
> 可以调用你写好的配置模板，配置模板要求：
> 
> https://github.com/Toperlock/sing-box-subscribe/blob/main/instructions/README.md#config-template-files
> 
> ![image](https://private-user-images.githubusercontent.com/86833913/349852452-bf22ff1d-b3f4-452f-9418-c53552455779.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODc2NjAsIm5iZiI6MTcyMTI4NzM2MCwicGF0aCI6Ii84NjgzMzkxMy8zNDk4NTI0NTItYmYyMmZmMWQtYjNmNC00NTJmLTk0MTgtYzUzNTUyNDU1Nzc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA3MjI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYmNlNTUzMzA1MzRjNWI3ZDRhNTRjOWRiNzA4NDA3NjZhZTk0Y2Y3NjNlMDliZTQ4NWFmZTYzZDkxMWE3OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q5rQKranamzD0YFyWKNKXh3gwQDLxbt5A23QKprWwSo)

您好，感谢您的回答。我可能表述的不太清楚，导致您误解了我的意思，您说的这些我都清楚，我真实是想知道以下内容：
1. `Edit TEMP_JSON_DATA` 的默认值可不可以修改，如果可以的话，要如何修改
2. `&file` 后的值可不可以不填直链，您截图的就是github托管的链接，而咱部署该项目的服务器上已经有模版文件了，我想知道有没有接口能让它直接调用它本地的，而不是我再通过nginx给这个配置文件弄个直链方便外部访问

**Comment by Toperlock** [comment]
修改展示的 Edit TEMP_JSON_DATA 内容文件：
├─api
│      app.py
└─templates
│      index.html

配置文件只要在 config_template 目录下就可以直接调用（用数字1代表第一个模板）：
├─config_template
│      你的模板.json
│      模板2.json

**Comment by FaithAluten** [comment]
感谢，已解决
