### ISSUE TITLE
相同的节点，转换完到客户端就会报错。

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#87]
### 描述

比如出现节点1，转换出来，相同的文件名节点1出现两个导入到客户端就会报错。
![IMG_20240718_231656](https://github.com/user-attachments/assets/5138d474-9209-484c-b0c2-de55f417096d)
![IMG_20240718_231606](https://github.com/user-attachments/assets/ae83ac78-b297-46ff-a221-fd3b5d50555a)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by onlyno999** [comment]
这个大神可以改进一下。

**Comment by Toperlock** [comment]
我不信

![PixPin_2024-07-19_10-28-43](https://github.com/user-attachments/assets/d398ad78-3f87-4b8f-8036-ce6d4b388c39)

**Comment by onlyno999** [comment]
> 我信
> 
> ![PixPin_2024-07-19_10-28-43](https://private-user-images.githubusercontent.com/86833913/350204403-d398ad78-3f87-4b8f-8036-ce6d4b388c39.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjY2NjMsIm5iZiI6MTcyMTM2NjM2MywicGF0aCI6Ii84NjgzMzkxMy8zNTAyMDQ0MDMtZDM5OGFkNzgtM2Y4Ny00YjhmLTgwMzYtY2U2ZDRiMzg4YzM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA1MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNWM3ZDVjYWQ0NjAzMjNjOTQ5YjBlM2M0Y2FjMGUwZTMzYTJkZmZkZDUzNjI3NmIwNDhkOGRiYzBjNmM5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyA3uiPAK9P71lo7-YYBeh4ecmxcrI6Q-4FItwm6HHQ) [ ![PixPin_2024-07-19_10-28-43](https://private-user-images.githubusercontent.com/86833913/350204403-d398ad78-3f87-4b8f-8036-ce6d4b388c39.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjY2NjMsIm5iZiI6MTcyMTM2NjM2MywicGF0aCI6Ii84NjgzMzkxMy8zNTAyMDQ0MDMtZDM5OGFkNzgtM2Y4Ny00YjhmLTgwMzYtY2U2ZDRiMzg4YzM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA1MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNWM3ZDVjYWQ0NjAzMjNjOTQ5YjBlM2M0Y2FjMGUwZTMzYTJkZmZkZDUzNjI3NmIwNDhkOGRiYzBjNmM5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyA3uiPAK9P71lo7-YYBeh4ecmxcrI6Q-4FItwm6HHQ) ](https://private-user-images.githubusercontent.com/86833913/350204403-d398ad78-3f87-4b8f-8036-ce6d4b388c39.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjY2NjMsIm5iZiI6MTcyMTM2NjM2MywicGF0aCI6Ii84NjgzMzkxMy8zNTAyMDQ0MDMtZDM5OGFkNzgtM2Y4Ny00YjhmLTgwMzYtY2U2ZDRiMzg4YzM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA1MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNWM3ZDVjYWQ0NjAzMjNjOTQ5YjBlM2M0Y2FjMGUwZTMzYTJkZmZkZDUzNjI3NmIwNDhkOGRiYzBjNmM5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyA3uiPAK9P71lo7-YYBeh4ecmxcrI6Q-4FItwm6HHQ) [ ](https://private-user-images.githubusercontent.com/86833913/350204403-d398ad78-3f87-4b8f-8036-ce6d4b388c39.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNjY2NjMsIm5iZiI6MTcyMTM2NjM2MywicGF0aCI6Ii84NjgzMzkxMy8zNTAyMDQ0MDMtZDM5OGFkNzgtM2Y4Ny00YjhmLTgwMzYtY2U2ZDRiMzg4YzM5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA1MTkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzNWM3ZDVjYWQ0NjAzMjNjOTQ5YjBlM2M0Y2FjMGUwZTMzYTJkZmZkZDUzNjI3NmIwNDhkOGRiYzBjNmM5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nyA3uiPAK9P71lo7-YYBeh4ecmxcrI6Q-4FItwm6HHQ)


你看第1张图。节点 1 2  节点 1 2 然后他转换出来就这样了。导入。sing box 就直接报错。

**Comment by Toperlock** [comment]
我意思是，我的转换不会出现节点名重复的问题。

你可以录个操作视频给我看看

**Comment by onlyno999** [comment]
> 我的意思是，我的转换不会出现节点名重复的问题。
> 
> 你可以录一个操作视频给我看看

https://sing-box-subscribe-doraemon.vercel.app/config/https:/chromegoclash.marcol.top/


直接导入。sing box 你就能看到哪里有错误。

**Comment by Toperlock** [comment]
我单独打开 https:/chromegoclash.marcol.top/
得到的 `data.yaml`格式都不正确
![image](https://github.com/user-attachments/assets/2f1fdaf7-1bca-453b-b934-d4916182d115)
请你把下发的clash格式内容修改正确，我再去测试

**Comment by Toperlock** [comment]
![image](https://github.com/user-attachments/assets/c063c493-3ff7-4d7f-a002-b44c46d388c5)
端口跳跃请用符合规范的参数

**Comment by Toperlock** [comment]
![image](https://github.com/user-attachments/assets/f69463ef-93cf-4d0c-a031-4e50ef337983)
链接屏蔽，我代码执行不了，不能测试

**Comment by Toperlock** [comment]
如果我直接用浏览器打开，用你下发的 `data.yaml` 文件，转换是没有问题。

![image](https://github.com/user-attachments/assets/1bdaa7f3-b110-49d5-9d02-cd3dbec8bed6)

**Comment by Toperlock** [comment]
应该可以了

**Comment by onlyno999** [comment]
> 应该可以

这样可以了，看吧，还是你大神出手就搞定了。
