### ISSUE TITLE
改进：能否考虑从机场导入节点时就排除一些协议。

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#88]
### 描述

如果订阅里面有VLESS ,VMESS，HY，我需要排除订阅中。VLESS协议。只留下。VMESS，HY协议。用 LINK&enn=VLESS

请问大佬用下面这种怎么实现？

方法二弄好了，用的enn参数，','分隔过滤关键词 eg：
/config/URL_LINK&enn=网站,剩余流量

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
`enn`参数是排除关键词
`eps`才是排除协议

https://sing-box-subscribe-doraemon.vercel.app/config/https:/chromegoclash.marcol.top&eps=vmess
