### ISSUE TITLE
`enn`参数是排除关键词

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#89]
`enn`参数是排除关键词
`eps`才是排除协议

https://sing-box-subscribe-doraemon.vercel.app/config/https:/chromegoclash.marcol.top&eps=vmess

_Originally posted by @Toperlock in https://github.com/Toperlock/sing-box-subscribe/issues/88#issuecomment-2247106561_
         
好像不同类型的就只能排出一个。大佬看是不是这样子。

https://sing-box-subscribe-doraemon.vercel.app/config/https:/chromegoclash.marcol.top&eps=hysteria,hysteria2,shadowtls,shadowsocks

**Comment by Toperlock** [comment]
![image](https://github.com/user-attachments/assets/d26fabce-fcb7-484d-9f5d-fb995dd1dab0)
按这些文件名的协议

https://sing-box-subscribe-doraemon.vercel.app/config/https:/chromegoclash.marcol.top&eps=hysteria,hysteria2,ss

**Comment by onlyno999** [comment]
感谢大佬不厌其烦的指导。
