### ISSUE TITLE
ua

### ISSUE THREAD

**Issue by ldh1983** [Toperlock/sing-box-subscribe#9]
能否每个订阅分开使用ua？

**Comment by Toperlock** [comment]
你需要哪两个ua？

**Comment by ldh1983** [comment]
不同订阅需要不同ua刷出来才能用，只要可以一个订阅设置一个ua就能解决问题。当然是支持越多ua越好。

**Comment by Toperlock** [comment]
> 不同订阅需要不同ua刷出来才能用，只要可以一个订阅设置一个ua就能解决问题。当然是支持越多ua越好。

目前脚本很难实现不同订阅设置不同UA，后续有头绪了会改进。
你可以通过机场提供的订阅连接后面加`&flag=clash`，或者`&flag=clashmeta`，`&flag=sing-box`来实现，这种需要问问你的机场是否支持添加`&flag=`

**Comment by Toperlock** [comment]
弄好了 [bfe00b7](https://github.com/Toperlock/sing-box-subscribe/commit/bfe00b7d8c849d895deab8cca7004b220649bdbd)

**Comment by ldh1983** [comment]
谢谢。
