### ISSUE TITLE
刚刚更新的打不开网站

### ISSUE THREAD

**Issue by KINGYJL** [Toperlock/sing-box-subscribe#90]
### 描述

4天前更新的，打不开网站，从vercel上，咋回事？佬。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
需要代理才能访问vercel域名
