### ISSUE TITLE
请大佬指点：指定名称，指定协议，参数写法。

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#92]
### 描述

已知的排除参数。
用的enn参数，','分隔过滤关键词eg：
排除名称。
/config/URL&LINK&enn=美国,

排除协议 
/config/URL&&eps=vless

未知的指定参数。请大佬指点。

求指定的名称？一个机场太多乱七八糟的，只想指定如香港。

/config/URL&???=香港,台湾

https://sing-box-subscribe-doraemon.vercel.app/config/https://moistr.freenods.sbs/mianfeicf

求指定协议？
/config/URL&???=vmess

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
只能排除，不能包括

**Comment by onlyno999** [comment]
> 只能排除，不能包括

大佬你行的，你分分钟搞定的事 嘿嘿嘿嘿
