### ISSUE TITLE
不同类型订阅链接支持问题

### ISSUE THREAD

**Issue by qcyhub** [Toperlock/sing-box-subscribe#93]
### 描述

目前是否只支持订阅链接为只包含节点的那种，如果订阅链接默认为配置文件，就是粘贴浏览器打开是默认下载clash.yaml文件，或者直接显示配置文件的这种，是不是不支持，能否做到支持，非常感谢！

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
clash.yaml配置文件里有 `proxies` 字段就支持转换

`proxy-providers`不支持解析

**Comment by Toperlock** [comment]
就连小火箭都不支持解析 `proxy-providers`

**Comment by qcyhub** [comment]
我在openwrt上测试的shellcrash 用的如下链接格式
http://127.0.0.1:5000/config/订阅链接&file=规则模板.json
我用docker搭建的您的后端。
订阅链接如果 浏览器打开为base64编码也就是纯节点的订阅链接，一切ok
订阅链接切换为 浏览器打开直接下载yaml文件 或者打开直接显示为yaml配置内容的 这两种类型订阅链接，就无法订阅成功。
而且两种配置内容中都有proxies 字段，非常正常的clash配置文件格式。
如果使用clash的增强版本的那个后端 这几种链接都是ok的。 但是我想用您的singbox专用的后端。这个问题无法解决.

**Comment by Toperlock** [comment]
看看你的 docker 运行日志提示什么报错

**Comment by qcyhub** [comment]
根据您的提示 查看日志找到了原因，非常感谢，是某个分组没有节点的话会报错，删除对应分组即可，应该添加一个直连也可以，我会试试。
![Snipaste_2024-08-09_20-35-07](https://github.com/user-attachments/assets/6996b2ed-30f8-4676-88c8-93dde6a30aa0)

**Comment by qcyhub** [comment]
另外有个小问题，就是我看您提供的模板中以及描述中没有涉及链式代理这一块，比如用"detour"字段，不知道是否支持。

**Comment by Toperlock** [comment]
你的主文件没更新，这问题以前就解决了
[main.py](https://github.com/Toperlock/sing-box-subscribe/blob/main/main.py#L483)

**Comment by qcyhub** [comment]
如果您能提供同步最新版本的docker镜像 那就太好了，不过非常感激你能提供这么棒的程序！
