### ISSUE TITLE
下午突然就这样。

### ISSUE THREAD

**Issue by onlyno999** [Toperlock/sing-box-subscribe#94]
### 描述

using Web Server Gateway Interface (WSGI)

Traceback (most recent call last):
File "/var/task/main.py", line 1, in <module>
import json, os, tool, time, requests, sys, importlib, argparse, yaml, ruamel.yaml
File "/var/task/tool.py", line 4, in <module>
with warnings.catch_warnings(action="ignore", category=CryptographyDeprecationWarning):
TypeError: __init__() got an unexpected keyword argument 'action'

提示远程500
https://sing-box-subscribe-six-ecru.vercel.app/config/

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Pallpop** [comment]
咋回事捏？俺也500了
