### ISSUE TITLE
提供多个机场的URL时，如果其中有一个机场出错，程序在跳过该机场时会出错

### ISSUE THREAD

**Issue by PullGuy** [Toperlock/sing-box-subscribe#95]
### 描述

报错信息如下：
![image](https://github.com/user-attachments/assets/3179b8b5-4eae-4f43-83cc-48970034dcb4)

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
#79

**Comment by PullGuy** [comment]
发生错误的位置不一样。我这个是在这一段出现的错误，我不太敢改，怕改乱了。
![image](https://github.com/user-attachments/assets/7b4b2eb7-a8f9-4a3d-8774-d3563e9c0e5c)

**Comment by Toperlock** [comment]
![image](https://github.com/user-attachments/assets/6c3a3d92-317f-4f42-b8ab-ff3aff1ec0bd)

应该可以了

**Comment by PullGuy** [comment]
非常感谢！
