### ISSUE TITLE
更新之后，转换失败了。

### ISSUE THREAD

**Issue by Teda9** [Toperlock/sing-box-subscribe#97]
### 描述

vercel 部署的， 之前可以正常更新的。 8.08 日之后，点更新订阅不成功。
/congfig 形式提示 
![image](https://github.com/user-attachments/assets/e9f6eaa7-7236-4666-9348-63fa56e06ee0)
{
    "status": "error"
}
手机上面更新链接提示这个显示 500 错误。
我自己的配置没改动啥。我自己的链接是通用的 base64 链接，能正常打开的。
vercel 安装的网页配置页面能正常打开，添加好链接之后  Select and Generate 就也还是出现上述的截图页面。

也清除过缓存，但是问题没有解决。

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
重新部署

https://github.com/Toperlock/sing-box-subscribe/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2

**Comment by Teda9** [comment]
> 重新部署
> 
> https://github.com/Toperlock/sing-box-subscribe/blob/main/docs/vercel-cn.md#%E5%A6%82%E4%BD%95%E9%87%8D%E6%96%B0%E9%83%A8%E7%BD%B2

Redeploy  没成功， 我删除重新再 部署就好了。
