### ISSUE TITLE
clash格式的节点ws-opts参数的path部分转换失败变成空值

### ISSUE THREAD

**Issue by xingmiye** [Toperlock/sing-box-subscribe#99]
### 描述

以下是一个clash的节点（关键信息用google域名和IP和*号代替）
```
proxies:
  - {name: clash节点, server: 8.8.8.8, port: 443, type: vless, uuid: ********-****-****-********, tls: true, tfo: false, servername: google.com, network: ws, ws-opts: {path: /************', headers: {Host: google.com}}, udp: true}
```
以下是通过sing-box-subscribe转换后的节点，path部分只剩下一个斜杠/，后面的部分丢失了，导致节点无法正常工作，手动把path补全其他部分保持不变后正常工作
```
    {
      "tag": "clash节点",
      "type": "vless",
      "server": "8.8.8.8",
      "server_port": 443,
      "uuid": "********-****-****-********",
      "packet_encoding": "xudp",
      "tls": {
        "enabled": true,
        "insecure": true,
        "server_name": "google.com"
      },
      "transport": {
        "type": "ws",
        "path": "/",
        "headers": {
          "Host": "google.com"
        },
        "early_data_header_name": "Sec-WebSocket-Protocol",
        "max_early_data": 636
      }
    }
```

### 完整性要求

- [X] 我保证阅读了reademe文档，了解所有sing-box-subscrib使用参数的含义与工作流程。
- [X] 我保证转换的订阅链接可以在浏览器打开，并且有内容。

**Comment by Toperlock** [comment]
请给出具体的path字段内容

**Comment by xingmiye** [comment]
比如：
path: /123
或者
path: /aa1
好像只要是path: /后面包含数字，转换后都会变成空值

**Comment by Toperlock** [comment]
真有问题，请你提供具体的path值谢谢
![image](https://github.com/user-attachments/assets/2da50800-f88f-41ae-ab94-5988e2646c72)


![image](https://github.com/user-attachments/assets/1b66ac50-e536-427a-948e-b30ab7f8a5a2)

**Comment by xingmiye** [comment]
我也是用大佬你这个“/147524”，转换以后确实只剩下“/”。
不过没事了，感谢大佬回复
可能原因是因为我用的是https://registry.hub.docker.com/r/hestudy/sing-box-subscribe/这个docker版，这个的作者没有及时更新，抱歉打扰了
